--
-- PostgreSQL database dump
--

\restrict hCxehQa7qRf5Apw8cU00RuIBTZVr8jyKNYD9TrBsbdo4HBQOKoDw4ulWgaY5nGk

-- Dumped from database version 14.20 (Ubuntu 14.20-0ubuntu0.22.04.1)
-- Dumped by pg_dump version 14.20 (Ubuntu 14.20-0ubuntu0.22.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: Category; Type: TABLE; Schema: public; Owner: ppj-pralon
--

CREATE TABLE public."Category" (
    id bigint NOT NULL,
    name character varying(256) NOT NULL,
    description text NOT NULL,
    status character varying(100) NOT NULL
);


ALTER TABLE public."Category" OWNER TO "ppj-pralon";

--
-- Name: Category_id_seq; Type: SEQUENCE; Schema: public; Owner: ppj-pralon
--

ALTER TABLE public."Category" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Category_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Customers; Type: TABLE; Schema: public; Owner: ppj-pralon
--

CREATE TABLE public."Customers" (
    id bigint NOT NULL,
    first_name character varying(256) NOT NULL,
    last_name character varying(256),
    address text,
    email character varying(256),
    phone character varying(30)
);


ALTER TABLE public."Customers" OWNER TO "ppj-pralon";

--
-- Name: Customers_id_seq; Type: SEQUENCE; Schema: public; Owner: ppj-pralon
--

ALTER TABLE public."Customers" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Customers_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Product; Type: TABLE; Schema: public; Owner: ppj-pralon
--

CREATE TABLE public."Product" (
    id bigint NOT NULL,
    name character varying(256) NOT NULL,
    description text NOT NULL,
    status character varying(100) NOT NULL,
    price double precision NOT NULL,
    category bigint NOT NULL
);


ALTER TABLE public."Product" OWNER TO "ppj-pralon";

--
-- Name: Product_id_seq; Type: SEQUENCE; Schema: public; Owner: ppj-pralon
--

ALTER TABLE public."Product" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Product_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: SaleDetails; Type: TABLE; Schema: public; Owner: ppj-pralon
--

CREATE TABLE public."SaleDetails" (
    id bigint NOT NULL,
    price double precision NOT NULL,
    quantity integer NOT NULL,
    total_detail double precision NOT NULL,
    product bigint NOT NULL,
    sale bigint NOT NULL
);


ALTER TABLE public."SaleDetails" OWNER TO "ppj-pralon";

--
-- Name: SaleDetails_id_seq; Type: SEQUENCE; Schema: public; Owner: ppj-pralon
--

ALTER TABLE public."SaleDetails" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."SaleDetails_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Sales; Type: TABLE; Schema: public; Owner: ppj-pralon
--

CREATE TABLE public."Sales" (
    id bigint NOT NULL,
    date_added timestamp with time zone NOT NULL,
    sub_total double precision NOT NULL,
    grand_total double precision NOT NULL,
    amount_payed double precision NOT NULL,
    amount_change double precision NOT NULL,
    customer bigint NOT NULL,
    transaction_number character varying(20) NOT NULL
);


ALTER TABLE public."Sales" OWNER TO "ppj-pralon";

--
-- Name: Sales_id_seq; Type: SEQUENCE; Schema: public; Owner: ppj-pralon
--

ALTER TABLE public."Sales" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Sales_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: ppj-pralon
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO "ppj-pralon";

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: ppj-pralon
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: ppj-pralon
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO "ppj-pralon";

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: ppj-pralon
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: ppj-pralon
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO "ppj-pralon";

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: ppj-pralon
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: ppj-pralon
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO "ppj-pralon";

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: ppj-pralon
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO "ppj-pralon";

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: ppj-pralon
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: ppj-pralon
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: ppj-pralon
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO "ppj-pralon";

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: ppj-pralon
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: authentication_profile; Type: TABLE; Schema: public; Owner: ppj-pralon
--

CREATE TABLE public.authentication_profile (
    id bigint NOT NULL,
    avatar character varying(100) NOT NULL,
    date_of_birth date,
    bio text NOT NULL,
    nama_lengkap character varying(500) NOT NULL,
    user_id integer NOT NULL,
    alamat text NOT NULL
);


ALTER TABLE public.authentication_profile OWNER TO "ppj-pralon";

--
-- Name: authentication_profile_id_seq; Type: SEQUENCE; Schema: public; Owner: ppj-pralon
--

ALTER TABLE public.authentication_profile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.authentication_profile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: ppj-pralon
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO "ppj-pralon";

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: ppj-pralon
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: ppj-pralon
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO "ppj-pralon";

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: ppj-pralon
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: ppj-pralon
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO "ppj-pralon";

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: ppj-pralon
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: ppj-pralon
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO "ppj-pralon";

--
-- Name: pegawai_absensi; Type: TABLE; Schema: public; Owner: ppj-pralon
--

CREATE TABLE public.pegawai_absensi (
    id bigint NOT NULL,
    tanggal date NOT NULL,
    jam_masuk time without time zone,
    jam_keluar time without time zone,
    status character varying(10) NOT NULL,
    pegawai_id bigint NOT NULL
);


ALTER TABLE public.pegawai_absensi OWNER TO "ppj-pralon";

--
-- Name: pegawai_absensi_id_seq; Type: SEQUENCE; Schema: public; Owner: ppj-pralon
--

ALTER TABLE public.pegawai_absensi ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pegawai_absensi_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pegawai_gaji; Type: TABLE; Schema: public; Owner: ppj-pralon
--

CREATE TABLE public.pegawai_gaji (
    id bigint NOT NULL,
    minggu_mulai date NOT NULL,
    minggu_selesai date NOT NULL,
    total_hadir integer NOT NULL,
    total_gaji numeric(10,2) NOT NULL,
    status character varying(10) NOT NULL,
    pegawai_id bigint NOT NULL
);


ALTER TABLE public.pegawai_gaji OWNER TO "ppj-pralon";

--
-- Name: pegawai_gaji_id_seq; Type: SEQUENCE; Schema: public; Owner: ppj-pralon
--

ALTER TABLE public.pegawai_gaji ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pegawai_gaji_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pegawai_gajiborongan; Type: TABLE; Schema: public; Owner: ppj-pralon
--

CREATE TABLE public.pegawai_gajiborongan (
    id bigint NOT NULL,
    minggu_mulai date NOT NULL,
    minggu_selesai date NOT NULL,
    total_kg numeric(10,2) NOT NULL,
    harga_per_kg numeric(10,2) NOT NULL,
    total_gaji numeric(10,2) NOT NULL,
    status character varying(10) NOT NULL,
    pegawai_id bigint NOT NULL
);


ALTER TABLE public.pegawai_gajiborongan OWNER TO "ppj-pralon";

--
-- Name: pegawai_gajiborongan_id_seq; Type: SEQUENCE; Schema: public; Owner: ppj-pralon
--

ALTER TABLE public.pegawai_gajiborongan ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pegawai_gajiborongan_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pegawai_pegawai; Type: TABLE; Schema: public; Owner: ppj-pralon
--

CREATE TABLE public.pegawai_pegawai (
    id bigint NOT NULL,
    nama character varying(255) NOT NULL,
    posisi character varying(10) NOT NULL,
    tanggal_masuk date NOT NULL,
    status character varying(50) NOT NULL,
    gaji_harian numeric(10,2) NOT NULL
);


ALTER TABLE public.pegawai_pegawai OWNER TO "ppj-pralon";

--
-- Name: pegawai_pegawai_id_seq; Type: SEQUENCE; Schema: public; Owner: ppj-pralon
--

ALTER TABLE public.pegawai_pegawai ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pegawai_pegawai_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pegawai_pekerjaanborongan; Type: TABLE; Schema: public; Owner: ppj-pralon
--

CREATE TABLE public.pegawai_pekerjaanborongan (
    id bigint NOT NULL,
    minggu_mulai date NOT NULL,
    minggu_selesai date NOT NULL,
    total_kg numeric(10,2) NOT NULL,
    harga_per_kg numeric(10,2) NOT NULL,
    total_gaji numeric(10,2) NOT NULL,
    pegawai_id bigint NOT NULL
);


ALTER TABLE public.pegawai_pekerjaanborongan OWNER TO "ppj-pralon";

--
-- Name: pegawai_pekerjaanborongan_id_seq; Type: SEQUENCE; Schema: public; Owner: ppj-pralon
--

ALTER TABLE public.pegawai_pekerjaanborongan ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pegawai_pekerjaanborongan_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sales_customercategory; Type: TABLE; Schema: public; Owner: ppj-pralon
--

CREATE TABLE public.sales_customercategory (
    id bigint NOT NULL,
    name character varying(50) NOT NULL
);


ALTER TABLE public.sales_customercategory OWNER TO "ppj-pralon";

--
-- Name: sales_customercategory_id_seq; Type: SEQUENCE; Schema: public; Owner: ppj-pralon
--

ALTER TABLE public.sales_customercategory ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sales_customercategory_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: zetaapp_excelupload; Type: TABLE; Schema: public; Owner: ppj-pralon
--

CREATE TABLE public.zetaapp_excelupload (
    id bigint NOT NULL,
    excel_files character varying(100) NOT NULL
);


ALTER TABLE public.zetaapp_excelupload OWNER TO "ppj-pralon";

--
-- Name: zetaapp_excelupload_id_seq; Type: SEQUENCE; Schema: public; Owner: ppj-pralon
--

ALTER TABLE public.zetaapp_excelupload ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.zetaapp_excelupload_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: zetaapp_hutangpiutang; Type: TABLE; Schema: public; Owner: ppj-pralon
--

CREATE TABLE public.zetaapp_hutangpiutang (
    id bigint NOT NULL,
    jumlah numeric(20,2) NOT NULL,
    tanggal date NOT NULL,
    hutang_choice character varying(1) NOT NULL,
    keterangan text,
    owner_id integer
);


ALTER TABLE public.zetaapp_hutangpiutang OWNER TO "ppj-pralon";

--
-- Name: zetaapp_hutangpiutang_id_seq; Type: SEQUENCE; Schema: public; Owner: ppj-pralon
--

ALTER TABLE public.zetaapp_hutangpiutang ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.zetaapp_hutangpiutang_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: zetaapp_hutpegawai; Type: TABLE; Schema: public; Owner: ppj-pralon
--

CREATE TABLE public.zetaapp_hutpegawai (
    id bigint NOT NULL,
    jumlah numeric(20,2) NOT NULL,
    tanggal date NOT NULL,
    hutang_choice character varying(1) NOT NULL,
    keterangan text,
    pegawai_id bigint NOT NULL
);


ALTER TABLE public.zetaapp_hutpegawai OWNER TO "ppj-pralon";

--
-- Name: zetaapp_hutpegawai_id_seq; Type: SEQUENCE; Schema: public; Owner: ppj-pralon
--

ALTER TABLE public.zetaapp_hutpegawai ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.zetaapp_hutpegawai_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: zetaapp_karyawan; Type: TABLE; Schema: public; Owner: ppj-pralon
--

CREATE TABLE public.zetaapp_karyawan (
    id bigint NOT NULL,
    name character varying(255) NOT NULL
);


ALTER TABLE public.zetaapp_karyawan OWNER TO "ppj-pralon";

--
-- Name: zetaapp_karyawan_id_seq; Type: SEQUENCE; Schema: public; Owner: ppj-pralon
--

ALTER TABLE public.zetaapp_karyawan ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.zetaapp_karyawan_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: zetaapp_kategori; Type: TABLE; Schema: public; Owner: ppj-pralon
--

CREATE TABLE public.zetaapp_kategori (
    id bigint NOT NULL,
    nama character varying(255) NOT NULL
);


ALTER TABLE public.zetaapp_kategori OWNER TO "ppj-pralon";

--
-- Name: zetaapp_kategori_id_seq; Type: SEQUENCE; Schema: public; Owner: ppj-pralon
--

ALTER TABLE public.zetaapp_kategori ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.zetaapp_kategori_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: zetaapp_pegawai; Type: TABLE; Schema: public; Owner: ppj-pralon
--

CREATE TABLE public.zetaapp_pegawai (
    id bigint NOT NULL,
    nama character varying(100) NOT NULL,
    nip character varying(20) NOT NULL,
    jabatan character varying(50) NOT NULL,
    gaji numeric(10,2) NOT NULL,
    tanggal_masuk date NOT NULL
);


ALTER TABLE public.zetaapp_pegawai OWNER TO "ppj-pralon";

--
-- Name: zetaapp_pegawai_id_seq; Type: SEQUENCE; Schema: public; Owner: ppj-pralon
--

ALTER TABLE public.zetaapp_pegawai ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.zetaapp_pegawai_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: zetaapp_product; Type: TABLE; Schema: public; Owner: ppj-pralon
--

CREATE TABLE public.zetaapp_product (
    id bigint NOT NULL,
    sku character varying(100) NOT NULL,
    name character varying(200) NOT NULL
);


ALTER TABLE public.zetaapp_product OWNER TO "ppj-pralon";

--
-- Name: zetaapp_product_id_seq; Type: SEQUENCE; Schema: public; Owner: ppj-pralon
--

ALTER TABLE public.zetaapp_product ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.zetaapp_product_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: zetaapp_profito; Type: TABLE; Schema: public; Owner: ppj-pralon
--

CREATE TABLE public.zetaapp_profito (
    id bigint NOT NULL,
    nama_suplayer text NOT NULL,
    description text NOT NULL,
    date date NOT NULL,
    jumlah_brg numeric(20,2) NOT NULL,
    harga_jual numeric(20,2) NOT NULL,
    harga_beli numeric(20,2) NOT NULL
);


ALTER TABLE public.zetaapp_profito OWNER TO "ppj-pralon";

--
-- Name: zetaapp_profito2; Type: TABLE; Schema: public; Owner: ppj-pralon
--

CREATE TABLE public.zetaapp_profito2 (
    id bigint NOT NULL,
    tanggal date NOT NULL,
    nama_barang character varying(100) NOT NULL,
    solar numeric(15,0) NOT NULL,
    karung numeric(15,0) NOT NULL,
    ongkos_kirim numeric(15,0) NOT NULL,
    ongkos_muat numeric(15,0) NOT NULL,
    ongkos_sortir numeric(15,0) NOT NULL,
    ongkos_giling numeric(15,0) NOT NULL,
    hpp_per_kg numeric(15,0),
    profit numeric(15,0),
    profit_margin numeric(5,2),
    berat_input numeric(10,2) NOT NULL,
    berat_output numeric(10,2),
    harga_beli_per_kg numeric(15,0) NOT NULL,
    harga_jual_per_kg numeric(15,0) NOT NULL,
    susutan_persen numeric(5,2) NOT NULL,
    total_hpp numeric(15,0),
    total_revenue numeric(15,0),
    keterangan text,
    tabungan_persen numeric(5,2) NOT NULL,
    tabungan_total numeric(15,0),
    profit_saved boolean NOT NULL
);


ALTER TABLE public.zetaapp_profito2 OWNER TO "ppj-pralon";

--
-- Name: zetaapp_profito2_id_seq; Type: SEQUENCE; Schema: public; Owner: ppj-pralon
--

ALTER TABLE public.zetaapp_profito2 ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.zetaapp_profito2_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: zetaapp_profito_id_seq; Type: SEQUENCE; Schema: public; Owner: ppj-pralon
--

ALTER TABLE public.zetaapp_profito ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.zetaapp_profito_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: zetaapp_stock; Type: TABLE; Schema: public; Owner: ppj-pralon
--

CREATE TABLE public.zetaapp_stock (
    id bigint NOT NULL,
    quantity numeric(12,2) NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    product_id bigint NOT NULL
);


ALTER TABLE public.zetaapp_stock OWNER TO "ppj-pralon";

--
-- Name: zetaapp_stock_id_seq; Type: SEQUENCE; Schema: public; Owner: ppj-pralon
--

ALTER TABLE public.zetaapp_stock ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.zetaapp_stock_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: zetaapp_stockin; Type: TABLE; Schema: public; Owner: ppj-pralon
--

CREATE TABLE public.zetaapp_stockin (
    id bigint NOT NULL,
    quantity numeric(12,2) NOT NULL,
    reference character varying(200) NOT NULL,
    note text NOT NULL,
    received_at timestamp with time zone NOT NULL,
    product_id bigint NOT NULL,
    received_by_id integer
);


ALTER TABLE public.zetaapp_stockin OWNER TO "ppj-pralon";

--
-- Name: zetaapp_stockin_id_seq; Type: SEQUENCE; Schema: public; Owner: ppj-pralon
--

ALTER TABLE public.zetaapp_stockin ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.zetaapp_stockin_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: zetaapp_tabungan; Type: TABLE; Schema: public; Owner: ppj-pralon
--

CREATE TABLE public.zetaapp_tabungan (
    id bigint NOT NULL,
    nominal numeric(20,2) NOT NULL,
    description text NOT NULL,
    date date NOT NULL,
    owner_id integer
);


ALTER TABLE public.zetaapp_tabungan OWNER TO "ppj-pralon";

--
-- Name: zetaapp_tabungan_id_seq; Type: SEQUENCE; Schema: public; Owner: ppj-pralon
--

ALTER TABLE public.zetaapp_tabungan ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.zetaapp_tabungan_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: zetaapp_task; Type: TABLE; Schema: public; Owner: ppj-pralon
--

CREATE TABLE public.zetaapp_task (
    id bigint NOT NULL,
    title character varying(200) NOT NULL,
    complete boolean NOT NULL,
    created timestamp with time zone NOT NULL
);


ALTER TABLE public.zetaapp_task OWNER TO "ppj-pralon";

--
-- Name: zetaapp_task_id_seq; Type: SEQUENCE; Schema: public; Owner: ppj-pralon
--

ALTER TABLE public.zetaapp_task ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.zetaapp_task_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: zetaapp_transaksi; Type: TABLE; Schema: public; Owner: ppj-pralon
--

CREATE TABLE public.zetaapp_transaksi (
    id bigint NOT NULL,
    jumlah numeric(20,2) NOT NULL,
    tanggal date NOT NULL,
    keterangan text,
    transaksi_choice character varying(1),
    kategori_id bigint,
    owner_id integer
);


ALTER TABLE public.zetaapp_transaksi OWNER TO "ppj-pralon";

--
-- Name: zetaapp_transaksi_id_seq; Type: SEQUENCE; Schema: public; Owner: ppj-pralon
--

ALTER TABLE public.zetaapp_transaksi ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.zetaapp_transaksi_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: Category; Type: TABLE DATA; Schema: public; Owner: ppj-pralon
--

COPY public."Category" (id, name, description, status) FROM stdin;
1	besi	besi	ACTIVE
2	kertas	kertas	ACTIVE
3	Plastik	plastik	ACTIVE
4	Kristal	kristal	ACTIVE
5	emberan	emberan	ACTIVE
\.


--
-- Data for Name: Customers; Type: TABLE DATA; Schema: public; Owner: ppj-pralon
--

COPY public."Customers" (id, first_name, last_name, address, email, phone) FROM stdin;
1	hatami	mohamad	jogja	hatami391998@gmail.com	00397409325
\.


--
-- Data for Name: Product; Type: TABLE DATA; Schema: public; Owner: ppj-pralon
--

COPY public."Product" (id, name, description, status, price, category) FROM stdin;
1	besi a	besi a	ACTIVE	4800	1
2	kardus	kardus	ACTIVE	2000	2
3	pralon	pralon	ACTIVE	1800	1
4	Pralon campur	pralon campur	ACTIVE	1800	3
5	pralon pk	pralon pk	ACTIVE	3300	3
6	pralon pk 1	pralon pk 1	ACTIVE	4000	3
7	pralon abu	pralon abu	ACTIVE	1800	3
8	pralon mambo	pralon mambo	ACTIVE	1000	3
9	hd tutup	hd tuutp	ACTIVE	4499	5
10	LD galon	ld galon	ACTIVE	6500	5
11	Galon	galon PC	ACTIVE	5000	4
12	Ps kaca	ps kaca	ACTIVE	7500	4
13	Ps warna	ps warna	ACTIVE	2700	4
14	PC 	pc 	ACTIVE	3500	4
15	akralik	akraik	ACTIVE	3500	4
16	CD	cd	ACTIVE	7500	4
\.


--
-- Data for Name: SaleDetails; Type: TABLE DATA; Schema: public; Owner: ppj-pralon
--

COPY public."SaleDetails" (id, price, quantity, total_detail, product, sale) FROM stdin;
1	4000	100	400000	6	1
2	1800	800	1440000	4	1
\.


--
-- Data for Name: Sales; Type: TABLE DATA; Schema: public; Owner: ppj-pralon
--

COPY public."Sales" (id, date_added, sub_total, grand_total, amount_payed, amount_change, customer, transaction_number) FROM stdin;
1	2025-12-05 10:53:14.79465+07	1840000	0	1900000	60000	1	PPJ-20251205-LN6NI1
\.


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: ppj-pralon
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: ppj-pralon
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: ppj-pralon
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add user	4	add_user
14	Can change user	4	change_user
15	Can delete user	4	delete_user
16	Can view user	4	view_user
17	Can add content type	5	add_contenttype
18	Can change content type	5	change_contenttype
19	Can delete content type	5	delete_contenttype
20	Can view content type	5	view_contenttype
21	Can add session	6	add_session
22	Can change session	6	change_session
23	Can delete session	6	delete_session
24	Can view session	6	view_session
25	Can add karyawan	7	add_karyawan
26	Can change karyawan	7	change_karyawan
27	Can delete karyawan	7	delete_karyawan
28	Can view karyawan	7	view_karyawan
29	Can add kategori	8	add_kategori
30	Can change kategori	8	change_kategori
31	Can delete kategori	8	delete_kategori
32	Can view kategori	8	view_kategori
33	Can add pegawai	9	add_pegawai
34	Can change pegawai	9	change_pegawai
35	Can delete pegawai	9	delete_pegawai
36	Can view pegawai	9	view_pegawai
37	Can add profito	10	add_profito
38	Can change profito	10	change_profito
39	Can delete profito	10	delete_profito
40	Can view profito	10	view_profito
41	Can add tabungan	11	add_tabungan
42	Can change tabungan	11	change_tabungan
43	Can delete tabungan	11	delete_tabungan
44	Can view tabungan	11	view_tabungan
45	Can add task	12	add_task
46	Can change task	12	change_task
47	Can delete task	12	delete_task
48	Can view task	12	view_task
49	Can add hutang piutang	13	add_hutangpiutang
50	Can change hutang piutang	13	change_hutangpiutang
51	Can delete hutang piutang	13	delete_hutangpiutang
52	Can view hutang piutang	13	view_hutangpiutang
53	Can add hut pegawai	14	add_hutpegawai
54	Can change hut pegawai	14	change_hutpegawai
55	Can delete hut pegawai	14	delete_hutpegawai
56	Can view hut pegawai	14	view_hutpegawai
57	Can add transaksi	15	add_transaksi
58	Can change transaksi	15	change_transaksi
59	Can delete transaksi	15	delete_transaksi
60	Can view transaksi	15	view_transaksi
61	Can add excel upload	16	add_excelupload
62	Can change excel upload	16	change_excelupload
63	Can delete excel upload	16	delete_excelupload
64	Can view excel upload	16	view_excelupload
65	Can add profito2	17	add_profito2
66	Can change profito2	17	change_profito2
67	Can delete profito2	17	delete_profito2
68	Can view profito2	17	view_profito2
69	Can add product	18	add_product
70	Can change product	18	change_product
71	Can delete product	18	delete_product
72	Can view product	18	view_product
73	Can add stock	19	add_stock
74	Can change stock	19	change_stock
75	Can delete stock	19	delete_stock
76	Can view stock	19	view_stock
77	Can add stock in	20	add_stockin
78	Can change stock in	20	change_stockin
79	Can delete stock in	20	delete_stockin
80	Can view stock in	20	view_stockin
81	Can add customer	21	add_customer
82	Can change customer	21	change_customer
83	Can delete customer	21	delete_customer
84	Can view customer	21	view_customer
85	Can add category	22	add_category
86	Can change category	22	change_category
87	Can delete category	22	delete_category
88	Can view category	22	view_category
89	Can add product	23	add_product
90	Can change product	23	change_product
91	Can delete product	23	delete_product
92	Can view product	23	view_product
93	Can add pegawai	24	add_pegawai
94	Can change pegawai	24	change_pegawai
95	Can delete pegawai	24	delete_pegawai
96	Can view pegawai	24	view_pegawai
97	Can add gaji borongan	25	add_gajiborongan
98	Can change gaji borongan	25	change_gajiborongan
99	Can delete gaji borongan	25	delete_gajiborongan
100	Can view gaji borongan	25	view_gajiborongan
101	Can add gaji	26	add_gaji
102	Can change gaji	26	change_gaji
103	Can delete gaji	26	delete_gaji
104	Can view gaji	26	view_gaji
105	Can add absensi	27	add_absensi
106	Can change absensi	27	change_absensi
107	Can delete absensi	27	delete_absensi
108	Can view absensi	27	view_absensi
109	Can add pekerjaan borongan	28	add_pekerjaanborongan
110	Can change pekerjaan borongan	28	change_pekerjaanborongan
111	Can delete pekerjaan borongan	28	delete_pekerjaanborongan
112	Can view pekerjaan borongan	28	view_pekerjaanborongan
113	Can add sale	29	add_sale
114	Can change sale	29	change_sale
115	Can delete sale	29	delete_sale
116	Can view sale	29	view_sale
117	Can add sale detail	30	add_saledetail
118	Can change sale detail	30	change_saledetail
119	Can delete sale detail	30	delete_saledetail
120	Can view sale detail	30	view_saledetail
121	Can add customer category	31	add_customercategory
122	Can change customer category	31	change_customercategory
123	Can delete customer category	31	delete_customercategory
124	Can view customer category	31	view_customercategory
125	Can add profile	32	add_profile
126	Can change profile	32	change_profile
127	Can delete profile	32	delete_profile
128	Can view profile	32	view_profile
136	Can delete category	18	delete_category
137	Can view category	18	view_category
138	Can add product	19	add_product
139	Can change product	19	change_product
140	Can delete product	19	delete_product
141	Can view product	19	view_product
142	Can add pegawai	20	add_pegawai
143	Can change pegawai	20	change_pegawai
144	Can delete pegawai	20	delete_pegawai
145	Can view pegawai	20	view_pegawai
146	Can add gaji borongan	21	add_gajiborongan
147	Can change gaji borongan	21	change_gajiborongan
148	Can delete gaji borongan	21	delete_gajiborongan
149	Can view gaji borongan	21	view_gajiborongan
150	Can add gaji	22	add_gaji
151	Can change gaji	22	change_gaji
152	Can delete gaji	22	delete_gaji
153	Can view gaji	22	view_gaji
154	Can add absensi	23	add_absensi
155	Can change absensi	23	change_absensi
156	Can delete absensi	23	delete_absensi
157	Can view absensi	23	view_absensi
158	Can add pekerjaan borongan	24	add_pekerjaanborongan
159	Can change pekerjaan borongan	24	change_pekerjaanborongan
160	Can delete pekerjaan borongan	24	delete_pekerjaanborongan
161	Can view pekerjaan borongan	24	view_pekerjaanborongan
162	Can add sale	25	add_sale
163	Can change sale	25	change_sale
164	Can delete sale	25	delete_sale
165	Can view sale	25	view_sale
166	Can add sale detail	26	add_saledetail
167	Can change sale detail	26	change_saledetail
168	Can delete sale detail	26	delete_saledetail
169	Can view sale detail	26	view_saledetail
170	Can add customer category	27	add_customercategory
171	Can change customer category	27	change_customercategory
172	Can delete customer category	27	delete_customercategory
173	Can view customer category	27	view_customercategory
174	Can add profile	28	add_profile
175	Can change profile	28	change_profile
176	Can delete profile	28	delete_profile
177	Can view profile	28	view_profile
178	Can add profito2	29	add_profito2
179	Can change profito2	29	change_profito2
180	Can delete profito2	29	delete_profito2
181	Can view profito2	29	view_profito2
182	Can add product	30	add_product
183	Can change product	30	change_product
184	Can delete product	30	delete_product
185	Can view product	30	view_product
186	Can add stock	31	add_stock
187	Can change stock	31	change_stock
188	Can delete stock	31	delete_stock
189	Can view stock	31	view_stock
190	Can add stock in	32	add_stockin
191	Can change stock in	32	change_stockin
192	Can delete stock in	32	delete_stockin
193	Can view stock in	32	view_stockin
\.


--
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: ppj-pralon
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
1	pbkdf2_sha256$1000000$KHAqBpbJrnFnkTojki0BH6$n8kL0+6wtbfCvm81aCB4ilfWWfV/u2oJvguuI2CFO9s=	2025-12-11 16:21:13.911823+07	t	tatam			tatam@gmail.com	t	t	2025-12-01 17:18:13.589546+07
\.


--
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: ppj-pralon
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: ppj-pralon
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: authentication_profile; Type: TABLE DATA; Schema: public; Owner: ppj-pralon
--

COPY public.authentication_profile (id, avatar, date_of_birth, bio, nama_lengkap, user_id, alamat) FROM stdin;
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: ppj-pralon
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
1	2025-11-09 12:28:20.750975+07	1	Transfer	1	[{"added": {}}]	8	1
2	2025-11-09 12:28:24.052837+07	2	Cash	1	[{"added": {}}]	8	1
3	2025-11-16 14:49:39.66486+07	1	PK1-001 - Pralon PK 1	1	[{"added": {}}]	30	1
4	2025-11-16 14:49:56.520226+07	2	PK2-001 - PK-2	1	[{"added": {}}]	30	1
5	2025-11-16 14:50:08.60894+07	3	Abu-001 - Abu	1	[{"added": {}}]	30	1
6	2025-11-16 14:50:31.705373+07	1	PK1-001 - Pralon PK 1	2	[]	30	1
7	2025-11-16 14:50:38.17735+07	2	PK2-001 - Pralon PK-2	2	[{"changed": {"fields": ["Name"]}}]	30	1
8	2025-11-16 14:50:45.432527+07	3	Abu-001 - Pralon Abu	2	[{"changed": {"fields": ["Name"]}}]	30	1
9	2025-11-16 14:51:29.213522+07	4	GLG-PK1 - Gil.PK1	1	[{"added": {}}]	30	1
10	2025-11-16 14:51:49.239473+07	5	GLG-PK2 - Gil. PK 2	1	[{"added": {}}]	30	1
11	2025-11-16 14:52:03.45567+07	6	GLG-ABU1 - Gil. ABU 1	1	[{"added": {}}]	30	1
12	2025-11-16 14:52:23.180019+07	7	GLG-ABU2 - GIl. ABU 2	1	[{"added": {}}]	30	1
13	2025-11-16 14:52:44.52881+07	8	GLG-MAMBO - Gil. Mambo	1	[{"added": {}}]	30	1
14	2025-11-16 14:53:19.364913+07	9	GIl.-PKPLAVON - GIl. PK-PLAVON	1	[{"added": {}}]	30	1
15	2025-11-16 14:53:59.811048+07	10	Mambo - Mambo	1	[{"added": {}}]	30	1
16	2025-11-16 14:54:15.398275+07	11	PK-Plavon - Pralon PK Plavon	1	[{"added": {}}]	30	1
17	2025-11-16 14:54:21.998867+07	10	Mambo - Pralon Mambo	2	[{"changed": {"fields": ["Name"]}}]	30	1
18	2025-11-16 14:55:51.817772+07	12	Pralon Campur	1	[{"added": {}}]	30	1
19	2025-11-18 10:00:58.838128+07	1	Apin	1	[{"added": {}}]	7	1
20	2025-11-18 10:01:05.522247+07	2	Agung	1	[{"added": {}}]	7	1
21	2025-11-18 10:01:09.674115+07	3	Oman	1	[{"added": {}}]	7	1
22	2025-11-18 10:01:12.415557+07	4	Andi	1	[{"added": {}}]	7	1
23	2025-11-18 10:01:16.212487+07	5	Pak Amin	1	[{"added": {}}]	7	1
24	2025-11-18 10:01:21.572386+07	6	Pak Anis	1	[{"added": {}}]	7	1
25	2025-11-24 08:47:24.253384+07	3	Gajian	1	[{"added": {}}]	8	1
26	2025-11-24 08:48:00.634872+07	4	Kiriman	1	[{"added": {}}]	8	1
27	2025-11-24 08:48:07.864483+07	5	Setor	1	[{"added": {}}]	8	1
28	2025-11-24 08:48:29.175193+07	6	Tarik Tunai	1	[{"added": {}}]	8	1
29	2025-11-24 08:49:02.856381+07	7	Jajan/Ngopi	1	[{"added": {}}]	8	1
30	2025-11-24 09:02:42.495935+07	8	Pinjam	1	[{"added": {}}]	8	1
31	2025-12-04 20:30:01.680218+07	12	mesin	1	[{"added": {}}]	8	1
32	2025-12-04 20:30:09.839061+07	13	investasi	1	[{"added": {}}]	8	1
33	2025-12-04 20:30:15.325297+07	14	pengambilan	1	[{"added": {}}]	8	1
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: ppj-pralon
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	auth	user
5	contenttypes	contenttype
6	sessions	session
7	zetaapp	karyawan
8	zetaapp	kategori
9	zetaapp	pegawai
10	zetaapp	profito
11	zetaapp	tabungan
12	zetaapp	task
13	zetaapp	hutangpiutang
14	zetaapp	hutpegawai
15	zetaapp	transaksi
16	zetaapp	excelupload
17	zetaapp	profito2
18	zetaapp	product
19	zetaapp	stock
20	zetaapp	stockin
21	customers	customer
22	products	category
23	products	product
24	pegawai	pegawai
25	pegawai	gajiborongan
26	pegawai	gaji
27	pegawai	absensi
28	pegawai	pekerjaanborongan
29	sales	sale
30	sales	saledetail
31	sales	customercategory
32	authentication	profile
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: ppj-pralon
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2025-12-01 16:20:31.219062+07
2	auth	0001_initial	2025-12-01 16:20:31.481457+07
3	admin	0001_initial	2025-12-01 16:20:31.55461+07
4	admin	0002_logentry_remove_auto_add	2025-12-01 16:20:31.571052+07
5	admin	0003_logentry_add_action_flag_choices	2025-12-01 16:20:31.585476+07
6	contenttypes	0002_remove_content_type_name	2025-12-01 16:20:31.612704+07
7	auth	0002_alter_permission_name_max_length	2025-12-01 16:20:31.626615+07
8	auth	0003_alter_user_email_max_length	2025-12-01 16:20:31.646321+07
9	auth	0004_alter_user_username_opts	2025-12-01 16:20:31.664894+07
10	auth	0005_alter_user_last_login_null	2025-12-01 16:20:31.682714+07
11	auth	0006_require_contenttypes_0002	2025-12-01 16:20:31.687641+07
12	auth	0007_alter_validators_add_error_messages	2025-12-01 16:20:31.700594+07
13	auth	0008_alter_user_username_max_length	2025-12-01 16:20:31.730055+07
14	auth	0009_alter_user_last_name_max_length	2025-12-01 16:20:31.74651+07
15	auth	0010_alter_group_name_max_length	2025-12-01 16:20:31.762054+07
16	auth	0011_update_proxy_permissions	2025-12-01 16:20:31.776173+07
17	auth	0012_alter_user_first_name_max_length	2025-12-01 16:20:31.7916+07
18	authentication	0001_initial	2025-12-01 16:20:31.854056+07
19	authentication	0002_remove_profile_alamat	2025-12-01 16:20:31.873726+07
20	authentication	0003_profile_alamat_alter_profile_nama_lengkap	2025-12-01 16:20:31.935426+07
21	customers	0001_initial	2025-12-01 16:20:31.975928+07
22	pegawai	0001_initial	2025-12-01 16:20:32.107449+07
23	products	0001_initial	2025-12-01 16:20:32.176045+07
24	sales	0001_initial	2025-12-01 16:20:32.28902+07
25	sales	0002_sale_transaction_number	2025-12-01 16:20:32.32151+07
26	sales	0003_remove_sale_tax_amount_remove_sale_tax_percentage	2025-12-01 16:20:32.335019+07
27	sales	0004_customercategory	2025-12-01 16:20:32.373432+07
28	sessions	0001_initial	2025-12-01 16:20:32.422371+07
29	zetaapp	0001_initial	2025-12-01 16:20:32.661127+07
30	zetaapp	0002_excelupload	2025-12-01 16:20:32.682728+07
31	zetaapp	0003_alter_hutpegawai_tanggal_alter_transaksi_tanggal	2025-12-01 16:20:32.759945+07
32	zetaapp	0004_alter_transaksi_kategori_and_more	2025-12-01 16:20:32.806969+07
33	zetaapp	0005_transaksi_sale	2025-12-01 16:20:32.852588+07
34	zetaapp	0006_remove_transaksi_sale	2025-12-01 16:20:32.879954+07
35	zetaapp	0007_profito2	2025-12-01 16:20:32.906223+07
36	zetaapp	0008_product_stock_stockin	2025-12-01 16:20:33.023391+07
37	zetaapp	0009_rename_hpp_profito2_hpp_per_kg_and_more	2025-12-01 16:20:33.09731+07
38	zetaapp	0010_profito2_keterangan_profito2_tabungan_persen_and_more	2025-12-01 16:20:33.113192+07
39	zetaapp	0011_remove_tabungan_transaksi_choice_and_more	2025-12-01 16:20:33.170994+07
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: ppj-pralon
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
6g04s17bhp5oeys5ijqxs8gfgpmirak4	.eJxVjEEOwiAQRe_C2hBgOlRcuu8ZyAwMUjVtUtqV8e7apAvd_vfef6lI21rj1mSJY1YXZdXpd2NKD5l2kO803Wad5mldRta7og_a9DBneV4P9--gUqvf2gHiGSAwMVlBm3JfOgMgXfHBFofJC_VFCJwN2TDm5L3DUAw4ZiT1_gDdWjfz:1vDcdG:3UOktGSnOjKmy9IkSzSmhHvdB6azmMdl4bHwf_qSmnw	2025-11-11 05:52:34.006974+07
7qgoo1up1rq9l0gni7153lc8ovsom5ln	.eJxVjztrwzAURv-K0RyMbUVOndEpXUrJ0tFg9LiKbyNboAduCfnvleoM6XrOd4_QjYw8hmmMHtyIihxJTXbPTHB5hSUL9cWXiy2lXYJDUeZJ-bC-_LAKTP_Y_gtM3E_puqGMvVDaCS54DayW6qD3FaWw121X64bJFvhBA6dN3alKMCXbtmGdrmgjBOMp6leAgPon1W4D8ZNdT3bR6OY-hmCXgRwLzY2HXTGQgDO4TBpWVRlwY-x6jsGjgpNBec0yuPi3ls-dT_gOWQ7k_D6QrFFu9fRolBK833DAYGDjb9bN0aArenDpw2iKVxSRp86d3H8B1XJ13Q:1vLITw:pn38OIkWAB0ikbqlH9c_gleWZM7lpL2NIhygsPOfW34	2025-12-02 09:58:40.07881+07
eabohtig27p3q119plozb1fyc9nnee54	.eJxdkDFvwyAQRv-KxRxZtglO3TEZ2ypDO1qyDjhiGgwSnJVWUf57TZ0h7fredw-JKxtgpnGYE8bBavbMarZ5ZBLUGX0W-hP8KZQqeIpWlnlS3m0q34JGt79v_wRGSONy3XAhnjjvJEioUdRK78y24hy3pu1q0wjVIuwMAm_qTldSaNW2jehMxRspBSzRdEEka76X2rVnaQyXQ_DGxmk_EwXfs-fCgEu4KXpGdsKYSSOqKgNwLlyOMyWr8eCsOmdJcf5dq8fOB35Rlj07vvQs6wVEGAhOaeVpVgpTWqVV69P_MFlyuPJ3dDABFeA1FBLj8iPWFa_hZH1BQDD17MZuP1Ubgsg:1vLlpE:j4MqfO2T940odjMcgqi0I7og1XhjAToT8qh9jT47wlM	2025-12-03 17:18:36.341358+07
mmpio4dzxgulzn8igwabov5896knayg6	.eJxdkDFvwyAQRv-KxRxZtglO3TEZ2ypDO1qyDjhiGgwSnJVWUf57TZ0h7fredw-JKxtgpnGYE8bBavbMarZ5ZBLUGX0W-hP8KZQqeIpWlnlS3m0q34JGt79v_wRGSONy3XAhnjjvJEioUdRK78y24hy3pu1q0wjVIuwMAm_qTldSaNW2jehMxRspBSzRdEEka76X2rVnaQyXQ_DGxmk_EwXfs-fCgEu4KXpGdsKYSSOqKgNwLlyOMyWr8eCsOmdJcf5dq8fOB35Rlj07vvQs6wVEGAhOaeVpVgpTWqVV69P_MFlyuPJ3dDABFeA1FBLj8iPWFa_hZH1BQDD17MZuP1Ubgsg:1vPz9D:htGCSzTtUbddBxp5ZgOfrKYV2PKqd0aTs39lHXuJEj8	2025-12-15 08:20:39.270748+07
vquc8ywsyq4rqoql4x7cyatro1v6msca	.eJxdkMFugzAMhl8F5VwhoANCj-1xm3rYjkjISQykDYmUGLGp6ruPjB66Xb_v92_LN9bBTGM3B_SdVuzAcrZ7ZgLkFW0U6gJ2cKl0lrwWaYykDxvSd6fQHB_ZPwUjhDFOZzWgqOpSil71dcXLCtbpnENZFrwSgHnRvzSgyqao9o0oMuScA3IJSuxVvCosiKT777Xt1rIwuuXkbK_9dJyJnG3ZIenBBNwlLSM9oY-kKLMsAjDGLeeZglZ4MlpeoyQ__6blc88nflGULTu_tizqFXjoCIaw8TBLiSFsUstt9T9Mmgxu_AMNTEAJWAWJQL9-RJvkzQ3aJgQEU8vu7P4DOSqDnQ:1vQP6J:y5tMdF7Cx8vxxaN21EmCESEN8bXazGSL5SCAfWWd4yI	2025-12-16 19:03:23.842798+07
4e0nd9zvdxvkn9tjdivioho91qplnth5	.eJxdkMFugzAMhl8F5VwhoANCj-1xm3rYjkjISQykDYmUGLGp6ruPjB66Xb_v92_LN9bBTGM3B_SdVuzAcrZ7ZgLkFW0U6gJ2cKl0lrwWaYykDxvSd6fQHB_ZPwUjhDFOZzWgqOpSil71dcXLCtbpnENZFrwSgHnRvzSgyqao9o0oMuScA3IJSuxVvCosiKT777Xt1rIwuuXkbK_9dJyJnG3ZIenBBNwlLSM9oY-kKLMsAjDGLeeZglZ4MlpeoyQ__6blc88nflGULTu_tizqFXjoCIaw8TBLiSFsUstt9T9Mmgxu_AMNTEAJWAWJQL9-RJvkzQ3aJgQEU8vu7P4DOSqDnQ:1vRfKk:knBBancpXGuWPLYO5gPA6kdKZz2j-L68tUb8ohEg584	2025-12-20 06:35:30.822159+07
akun6h6p9ppg07q2o0xiz8z4adukn1rc	.eJxdkMFugzAMhl8F5VwhoANCj-1xm3rYjkjISQykDYmUGLGp6ruPjB66Xb_v92_LN9bBTGM3B_SdVuzAcrZ7ZgLkFW0U6gJ2cKl0lrwWaYykDxvSd6fQHB_ZPwUjhDFOZzWgqOpSil71dcXLCtbpnENZFrwSgHnRvzSgyqao9o0oMuScA3IJSuxVvCosiKT777Xt1rIwuuXkbK_9dJyJnG3ZIenBBNwlLSM9oY-kKLMsAjDGLeeZglZ4MlpeoyQ__6blc88nflGULTu_tizqFXjoCIaw8TBLiSFsUstt9T9Mmgxu_AMNTEAJWAWJQL9-RJvkzQ3aJgQEU8vu7P4DOSqDnQ:1vRgJK:vHf7AN4-ZQXN3aUaYlq3mtWfAdiLiFBuRgGS9DnyPgw	2025-12-20 07:38:06.249689+07
jhxyams9hzvw64dxih7isg7nrp3vuecz	.eJxdkMFugzAMhl8F5VwhoANCj-1xm3rYjkjISQykDYmUGLGp6ruPjB66Xb_v92_LN9bBTGM3B_SdVuzAcrZ7ZgLkFW0U6gJ2cKl0lrwWaYykDxvSd6fQHB_ZPwUjhDFOZzWgqOpSil71dcXLCtbpnENZFrwSgHnRvzSgyqao9o0oMuScA3IJSuxVvCosiKT777Xt1rIwuuXkbK_9dJyJnG3ZIenBBNwlLSM9oY-kKLMsAjDGLeeZglZ4MlpeoyQ__6blc88nflGULTu_tizqFXjoCIaw8TBLiSFsUstt9T9Mmgxu_AMNTEAJWAWJQL9-RJvkzQ3aJgQEU8vu7P4DOSqDnQ:1vTcrJ:uM_ds5tl-1uUspP5ji5ukpqCOF9NpkSkU0FmaXZNaEM	2025-12-25 16:21:13.920454+07
\.


--
-- Data for Name: pegawai_absensi; Type: TABLE DATA; Schema: public; Owner: ppj-pralon
--

COPY public.pegawai_absensi (id, tanggal, jam_masuk, jam_keluar, status, pegawai_id) FROM stdin;
\.


--
-- Data for Name: pegawai_gaji; Type: TABLE DATA; Schema: public; Owner: ppj-pralon
--

COPY public.pegawai_gaji (id, minggu_mulai, minggu_selesai, total_hadir, total_gaji, status, pegawai_id) FROM stdin;
\.


--
-- Data for Name: pegawai_gajiborongan; Type: TABLE DATA; Schema: public; Owner: ppj-pralon
--

COPY public.pegawai_gajiborongan (id, minggu_mulai, minggu_selesai, total_kg, harga_per_kg, total_gaji, status, pegawai_id) FROM stdin;
\.


--
-- Data for Name: pegawai_pegawai; Type: TABLE DATA; Schema: public; Owner: ppj-pralon
--

COPY public.pegawai_pegawai (id, nama, posisi, tanggal_masuk, status, gaji_harian) FROM stdin;
1	Andi	Borongan	2023-11-10	Aktif	0.00
\.


--
-- Data for Name: pegawai_pekerjaanborongan; Type: TABLE DATA; Schema: public; Owner: ppj-pralon
--

COPY public.pegawai_pekerjaanborongan (id, minggu_mulai, minggu_selesai, total_kg, harga_per_kg, total_gaji, pegawai_id) FROM stdin;
\.


--
-- Data for Name: sales_customercategory; Type: TABLE DATA; Schema: public; Owner: ppj-pralon
--

COPY public.sales_customercategory (id, name) FROM stdin;
\.


--
-- Data for Name: zetaapp_excelupload; Type: TABLE DATA; Schema: public; Owner: ppj-pralon
--

COPY public.zetaapp_excelupload (id, excel_files) FROM stdin;
\.


--
-- Data for Name: zetaapp_hutangpiutang; Type: TABLE DATA; Schema: public; Owner: ppj-pralon
--

COPY public.zetaapp_hutangpiutang (id, jumlah, tanggal, hutang_choice, keterangan, owner_id) FROM stdin;
\.


--
-- Data for Name: zetaapp_hutpegawai; Type: TABLE DATA; Schema: public; Owner: ppj-pralon
--

COPY public.zetaapp_hutpegawai (id, jumlah, tanggal, hutang_choice, keterangan, pegawai_id) FROM stdin;
1	750000.00	2025-12-04	H	hutnag terakhir	3
2	1850000.00	2025-12-04	H	hutang terakhir	4
3	200000.00	2025-12-04	H	pnjam	4
4	880000.00	2025-12-04	H	hutang terakhir	2
6	150000.00	2025-12-06	H	Bon	2
\.


--
-- Data for Name: zetaapp_karyawan; Type: TABLE DATA; Schema: public; Owner: ppj-pralon
--

COPY public.zetaapp_karyawan (id, name) FROM stdin;
1	Apin
2	Agung
3	Oman
4	Andi
5	Pak Amin
6	Pak Anis
\.


--
-- Data for Name: zetaapp_kategori; Type: TABLE DATA; Schema: public; Owner: ppj-pralon
--

COPY public.zetaapp_kategori (id, nama) FROM stdin;
1	Transfer
2	Cash
3	Gajian
4	Kiriman
5	Setor
6	Tarik Tunai
7	Jajan/Ngopi
8	Pinjam
12	mesin
13	investasi
14	pengambilan
\.


--
-- Data for Name: zetaapp_pegawai; Type: TABLE DATA; Schema: public; Owner: ppj-pralon
--

COPY public.zetaapp_pegawai (id, nama, nip, jabatan, gaji, tanggal_masuk) FROM stdin;
\.


--
-- Data for Name: zetaapp_product; Type: TABLE DATA; Schema: public; Owner: ppj-pralon
--

COPY public.zetaapp_product (id, sku, name) FROM stdin;
1	PK1-001	Pralon PK 1
2	PK2-001	Pralon PK-2
3	Abu-001	Pralon Abu
4	GLG-PK1	Gil.PK1
5	GLG-PK2	Gil. PK 2
6	GLG-ABU1	Gil. ABU 1
7	GLG-ABU2	GIl. ABU 2
8	GLG-MAMBO	Gil. Mambo
9	GIl.-PKPLAVON	GIl. PK-PLAVON
10	Mambo	Pralon Mambo
11	PK-Plavon	Pralon PK Plavon
12	PR-CAM	Pralon Campur
\.


--
-- Data for Name: zetaapp_profito; Type: TABLE DATA; Schema: public; Owner: ppj-pralon
--

COPY public.zetaapp_profito (id, nama_suplayer, description, date, jumlah_brg, harga_jual, harga_beli) FROM stdin;
\.


--
-- Data for Name: zetaapp_profito2; Type: TABLE DATA; Schema: public; Owner: ppj-pralon
--

COPY public.zetaapp_profito2 (id, tanggal, nama_barang, solar, karung, ongkos_kirim, ongkos_muat, ongkos_sortir, ongkos_giling, hpp_per_kg, profit, profit_margin, berat_input, berat_output, harga_beli_per_kg, harga_jual_per_kg, susutan_persen, total_hpp, total_revenue, keterangan, tabungan_persen, tabungan_total, profit_saved) FROM stdin;
1	2025-11-25	abu super	100	50	375	50	300	300	3175	1250000	16.45	2000.00	1900.00	2000	4000	5.00	6350000	7600000	\N	30.00	375000	t
\.


--
-- Data for Name: zetaapp_stock; Type: TABLE DATA; Schema: public; Owner: ppj-pralon
--

COPY public.zetaapp_stock (id, quantity, updated_at, product_id) FROM stdin;
\.


--
-- Data for Name: zetaapp_stockin; Type: TABLE DATA; Schema: public; Owner: ppj-pralon
--

COPY public.zetaapp_stockin (id, quantity, reference, note, received_at, product_id, received_by_id) FROM stdin;
\.


--
-- Data for Name: zetaapp_tabungan; Type: TABLE DATA; Schema: public; Owner: ppj-pralon
--

COPY public.zetaapp_tabungan (id, nominal, description, date, owner_id) FROM stdin;
\.


--
-- Data for Name: zetaapp_task; Type: TABLE DATA; Schema: public; Owner: ppj-pralon
--

COPY public.zetaapp_task (id, title, complete, created) FROM stdin;
\.


--
-- Data for Name: zetaapp_transaksi; Type: TABLE DATA; Schema: public; Owner: ppj-pralon
--

COPY public.zetaapp_transaksi (id, jumlah, tanggal, keterangan, transaksi_choice, kategori_id, owner_id) FROM stdin;
1	31938350.00	2025-11-13	Transfer masuk	P	1	1
2	2000000.00	2025-11-13	Mama masuk	P	1	1
3	460800.00	2025-11-13	bayar barang pralon	L	1	1
4	1300000.00	2025-11-13	dp barang pralon	L	1	1
5	36000.00	2025-11-13	makan bakso	L	1	1
6	100000.00	2025-11-13	Agung bon	L	1	1
7	350000.00	2025-11-13	Buat beli solar sama bensin	L	2	1
8	2600000.00	2025-11-13	Bayar ongkos kirim	L	1	1
9	20000.00	2025-11-13	makan	L	1	1
10	588000.00	2025-11-13	Joko Kobet	L	1	1
11	510000.00	2025-11-13	Feby	L	1	1
12	903100.00	2025-11-13	Pak mardi	L	1	1
13	793200.00	2025-11-13	Hutang mandiri	L	1	1
14	1452900.00	2025-11-13	Pak bukhori	L	1	1
15	701300.00	2025-11-13	handoyo	L	1	1
16	12000000.00	2025-11-13	bayar hutang	L	1	1
17	17500.00	2025-11-13	admin	L	1	1
18	504000.00	2025-11-14	tarik Tunai 150 bu titi, 50 bu titi pinjam, 150 solar, 100 bensin, 50 makan	L	2	1
19	15000.00	2025-11-14	makan	L	1	1
20	3072600.00	2025-11-14	bayar pak pardi	P	1	1
21	3100000.00	2025-11-14	baya pak pardi	L	1	1
22	200000.00	2025-11-14	bu bibit	L	1	1
23	3000000.00	2025-11-14	tabungan	L	1	1
24	764400.00	2025-11-14	harjiyo	L	1	1
25	3236850.00	2025-11-14	bayar hatami	P	1	1
26	796800.00	2025-11-14	parjono	L	1	1
27	191600.00	2025-11-14	sisa kirim pa tasri	P	1	1
28	1515200.00	2025-11-14	Pak dwi Suraynto	L	1	1
29	988200.00	2025-11-14	pak joko	L	1	1
30	7500.00	2025-11-14	admin	L	1	1
31	3000000.00	2025-11-15	tarik tunai(gajian,bensin dan meisn)	L	2	1
32	230000.00	2025-11-15	Gajian AGung	L	1	1
33	1000000.00	2025-11-15	Transfer Rogaya dan royati	L	1	1
34	488000.00	2025-11-15	bayar sisa pralon joko wirokerten	L	1	1
35	200000.00	2025-11-15	nikahan mbah zainal	L	1	1
36	90247.00	2025-11-15	bayar apket	L	1	1
37	150000.00	2025-11-16	tarik tunai	L	2	1
38	28000.00	2025-11-16	makan dan jajan	L	1	1
39	1000000.00	2025-11-17	Titip Joko pralon	L	1	1
40	10000000.00	2025-11-17	DP Pak Tasri	P	1	1
41	173000.00	2025-11-18	makan, solar dan bensin	L	1	1
42	604000.00	2025-11-18	DP pak pardi 500 rb dan bensin	L	1	1
43	5500.00	2025-11-18	makan	L	1	1
44	500000.00	2025-11-18	titip joko	L	1	1
45	30000.00	2025-11-18	beli sate kambing	L	1	1
46	40000.00	2025-11-18	servis kacamata	L	1	1
47	12500.00	2025-11-19	bayar makan	L	1	1
48	303000.00	2025-11-19	Buat solar 150 dan perjalanan solo	L	2	1
49	138500.00	2025-11-19	beli solar	L	1	1
50	7500000.00	2025-11-19	pinjam dana dari mandiri dan bca tabungan	P	1	1
51	16529500.00	2025-11-19	bayar praon pak pur	L	1	1
52	100000.00	2025-11-19	tarik atm untuk jajan	L	1	1
53	65000.00	2025-11-20	makan dan tf agung	L	1	1
54	212000.00	2025-11-21	tarik tunai 200 rb(bensin dan oli) dan makan 10 rb	L	1	1
55	102500.00	2025-11-21	tarik tunai dan tf andi	L	1	1
56	24048400.00	2025-11-21	Masuk nota pa tasri	P	1	1
57	2505000.00	2025-11-21	bayar ongkoss	L	1	1
58	202500.00	2025-11-21	isti pinjam	L	1	1
59	2100000.00	2025-11-21	pa pardi kirim barang	L	1	1
60	7000000.00	2025-11-21	bayar hutang	L	1	1
61	288000.00	2025-11-21	baya rbrg	L	1	1
62	887800.00	2025-11-21	bayar barang ang juju	L	1	1
63	1500000.00	2025-11-21	balikin dana hutang	L	1	1
64	2000000.00	2025-11-21	profit	L	1	1
65	27500.00	2025-11-21	ngofe	L	1	1
66	11000.00	2025-11-21	makan tokopedia	L	1	1
67	202000.00	2025-11-21	tarik tunai	L	1	1
68	17500.00	2025-11-22	makan dan ngofe	L	7	1
69	350000.00	2025-11-22	solar 150, bensin 100, pasang ban 75, sisa cekelan	L	6	1
70	15000.00	2025-11-22	makan	L	7	1
71	4000000.00	2025-11-22	bayar hutang	L	1	1
72	30000.00	2025-11-22	makan di sch	L	7	1
73	3000000.00	2025-11-22	Gajian anak-anak	L	3	1
74	11000.00	2025-11-24	makan	L	7	1
75	72000.00	2025-11-24	cuci motor, loundry dan ngopi	L	7	1
76	5000000.00	2025-11-24	pinjam dana tabungan	L	8	1
77	4000000.00	2025-11-25	transfer barang mama	P	4	1
78	250000.00	2025-11-25	buat solar dan bensin	L	6	1
79	586900.00	2025-11-25	bayar sisa oji	L	5	1
80	2000000.00	2025-11-25	dp pak slamet	L	4	1
81	55500.00	2025-11-25	bayar cloud	L	7	1
83	480000.00	2025-11-26	beli kjarung	L	2	1
84	14500.00	2025-11-26	beli makan	L	7	1
85	116500.00	2025-11-27	transfer ulfa dan makan	L	1	1
86	202500.00	2025-11-27	baya rorang setor dan transfer	L	5	1
88	200000.00	2025-11-27	bu titik	L	6	1
89	2000000.00	2025-11-27	dp mamak	P	4	1
90	620000.00	2025-11-27	indo paskaroja	L	14	1
91	10000000.00	2025-11-28	DP pka tasri	P	3	1
92	2896100.00	2025-11-28	Bayar Pak yudi cirebon	L	14	1
93	886400.00	2025-11-28	bayar sisa pak slamet dan makan	L	14	1
94	604000.00	2025-11-28	tarik tunai untuk muat dna lain lain	L	6	1
95	50000.00	2025-11-28	bon agung	L	8	1
96	150000.00	2025-11-28	bayar wifi	L	13	1
97	5000000.00	2025-11-28	bayar hutang pinjam	P	8	1
98	900000.00	2025-11-29	bayar hutang dana bca	P	8	1
99	2715000.00	2025-11-29	bayar pak pardi	L	5	1
100	22093300.00	2025-11-29	pak tasri masuk	P	4	1
101	7000000.00	2025-11-29	tiitp mama	L	1	1
102	2602500.00	2025-11-29	ongkos sopir	L	13	1
103	4500000.00	2025-11-29	bayar hutnag dan gajian kiriman	L	8	1
104	5000000.00	2025-11-29	dp pak pur	L	4	1
105	152500.00	2025-11-29	tranfser adry	L	8	1
106	200000.00	2025-11-29	transfer hatami	P	4	1
107	3000000.00	2025-11-29	gajian	L	3	1
108	100000.00	2025-11-30	tarik tunai	L	6	1
109	5500.00	2025-12-01	toko aila	L	1	1
110	3000000.00	2025-12-01	dp mamak	P	4	1
111	1500000.00	2025-12-01	dp pak rudi	L	14	1
112	189000.00	2025-12-01	bayar pak harjiyo	L	14	1
113	960000.00	2025-12-01	bayar pak mardi	L	14	1
114	120000.00	2025-12-02	loundry, bon agung, dan tiktok	L	13	1
115	150000.00	2025-12-03	bayar diesel	L	12	1
116	100000.00	2025-12-03	tarikan atm	L	7	1
117	5000000.00	2025-12-04	titip mamak	P	4	1
118	1500000.00	2025-12-04	bayar pak enjang	L	14	1
119	532000.00	2025-12-04	ongkos muat 400, makan dan admin	L	13	1
120	5000000.00	2025-12-04	pinjam dana bca	L	8	1
121	1840000.00	2025-12-05	Penjualan PPJ-20251205-LN6NI1	L	\N	\N
123	1000000.00	2025-12-06	Jajaj	L	4	1
\.


--
-- Name: Category_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ppj-pralon
--

SELECT pg_catalog.setval('public."Category_id_seq"', 1, true);


--
-- Name: Customers_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ppj-pralon
--

SELECT pg_catalog.setval('public."Customers_id_seq"', 1, false);


--
-- Name: Product_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ppj-pralon
--

SELECT pg_catalog.setval('public."Product_id_seq"', 1, false);


--
-- Name: SaleDetails_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ppj-pralon
--

SELECT pg_catalog.setval('public."SaleDetails_id_seq"', 2, true);


--
-- Name: Sales_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ppj-pralon
--

SELECT pg_catalog.setval('public."Sales_id_seq"', 1, true);


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ppj-pralon
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ppj-pralon
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ppj-pralon
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 193, true);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ppj-pralon
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ppj-pralon
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 2, true);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ppj-pralon
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- Name: authentication_profile_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ppj-pralon
--

SELECT pg_catalog.setval('public.authentication_profile_id_seq', 1, false);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ppj-pralon
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 33, true);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ppj-pralon
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 32, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ppj-pralon
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 39, true);


--
-- Name: pegawai_absensi_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ppj-pralon
--

SELECT pg_catalog.setval('public.pegawai_absensi_id_seq', 1, false);


--
-- Name: pegawai_gaji_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ppj-pralon
--

SELECT pg_catalog.setval('public.pegawai_gaji_id_seq', 1, false);


--
-- Name: pegawai_gajiborongan_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ppj-pralon
--

SELECT pg_catalog.setval('public.pegawai_gajiborongan_id_seq', 1, false);


--
-- Name: pegawai_pegawai_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ppj-pralon
--

SELECT pg_catalog.setval('public.pegawai_pegawai_id_seq', 1, false);


--
-- Name: pegawai_pekerjaanborongan_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ppj-pralon
--

SELECT pg_catalog.setval('public.pegawai_pekerjaanborongan_id_seq', 1, false);


--
-- Name: sales_customercategory_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ppj-pralon
--

SELECT pg_catalog.setval('public.sales_customercategory_id_seq', 1, false);


--
-- Name: zetaapp_excelupload_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ppj-pralon
--

SELECT pg_catalog.setval('public.zetaapp_excelupload_id_seq', 1, false);


--
-- Name: zetaapp_hutangpiutang_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ppj-pralon
--

SELECT pg_catalog.setval('public.zetaapp_hutangpiutang_id_seq', 1, false);


--
-- Name: zetaapp_hutpegawai_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ppj-pralon
--

SELECT pg_catalog.setval('public.zetaapp_hutpegawai_id_seq', 6, true);


--
-- Name: zetaapp_karyawan_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ppj-pralon
--

SELECT pg_catalog.setval('public.zetaapp_karyawan_id_seq', 6, true);


--
-- Name: zetaapp_kategori_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ppj-pralon
--

SELECT pg_catalog.setval('public.zetaapp_kategori_id_seq', 14, true);


--
-- Name: zetaapp_pegawai_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ppj-pralon
--

SELECT pg_catalog.setval('public.zetaapp_pegawai_id_seq', 1, false);


--
-- Name: zetaapp_product_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ppj-pralon
--

SELECT pg_catalog.setval('public.zetaapp_product_id_seq', 12, true);


--
-- Name: zetaapp_profito2_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ppj-pralon
--

SELECT pg_catalog.setval('public.zetaapp_profito2_id_seq', 1, true);


--
-- Name: zetaapp_profito_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ppj-pralon
--

SELECT pg_catalog.setval('public.zetaapp_profito_id_seq', 1, false);


--
-- Name: zetaapp_stock_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ppj-pralon
--

SELECT pg_catalog.setval('public.zetaapp_stock_id_seq', 1, false);


--
-- Name: zetaapp_stockin_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ppj-pralon
--

SELECT pg_catalog.setval('public.zetaapp_stockin_id_seq', 1, false);


--
-- Name: zetaapp_tabungan_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ppj-pralon
--

SELECT pg_catalog.setval('public.zetaapp_tabungan_id_seq', 1, false);


--
-- Name: zetaapp_task_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ppj-pralon
--

SELECT pg_catalog.setval('public.zetaapp_task_id_seq', 1, false);


--
-- Name: zetaapp_transaksi_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ppj-pralon
--

SELECT pg_catalog.setval('public.zetaapp_transaksi_id_seq', 123, true);


--
-- Name: Category Category_pkey; Type: CONSTRAINT; Schema: public; Owner: ppj-pralon
--

ALTER TABLE ONLY public."Category"
    ADD CONSTRAINT "Category_pkey" PRIMARY KEY (id);


--
-- Name: Customers Customers_pkey; Type: CONSTRAINT; Schema: public; Owner: ppj-pralon
--

ALTER TABLE ONLY public."Customers"
    ADD CONSTRAINT "Customers_pkey" PRIMARY KEY (id);


--
-- Name: Product Product_pkey; Type: CONSTRAINT; Schema: public; Owner: ppj-pralon
--

ALTER TABLE ONLY public."Product"
    ADD CONSTRAINT "Product_pkey" PRIMARY KEY (id);


--
-- Name: SaleDetails SaleDetails_pkey; Type: CONSTRAINT; Schema: public; Owner: ppj-pralon
--

ALTER TABLE ONLY public."SaleDetails"
    ADD CONSTRAINT "SaleDetails_pkey" PRIMARY KEY (id);


--
-- Name: Sales Sales_pkey; Type: CONSTRAINT; Schema: public; Owner: ppj-pralon
--

ALTER TABLE ONLY public."Sales"
    ADD CONSTRAINT "Sales_pkey" PRIMARY KEY (id);


--
-- Name: Sales Sales_transaction_number_key; Type: CONSTRAINT; Schema: public; Owner: ppj-pralon
--

ALTER TABLE ONLY public."Sales"
    ADD CONSTRAINT "Sales_transaction_number_key" UNIQUE (transaction_number);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: ppj-pralon
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: ppj-pralon
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: ppj-pralon
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: ppj-pralon
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: ppj-pralon
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: ppj-pralon
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: ppj-pralon
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: ppj-pralon
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: ppj-pralon
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: ppj-pralon
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: ppj-pralon
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: ppj-pralon
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: authentication_profile authentication_profile_pkey; Type: CONSTRAINT; Schema: public; Owner: ppj-pralon
--

ALTER TABLE ONLY public.authentication_profile
    ADD CONSTRAINT authentication_profile_pkey PRIMARY KEY (id);


--
-- Name: authentication_profile authentication_profile_user_id_key; Type: CONSTRAINT; Schema: public; Owner: ppj-pralon
--

ALTER TABLE ONLY public.authentication_profile
    ADD CONSTRAINT authentication_profile_user_id_key UNIQUE (user_id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: ppj-pralon
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: ppj-pralon
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: ppj-pralon
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: ppj-pralon
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: ppj-pralon
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: pegawai_absensi pegawai_absensi_pkey; Type: CONSTRAINT; Schema: public; Owner: ppj-pralon
--

ALTER TABLE ONLY public.pegawai_absensi
    ADD CONSTRAINT pegawai_absensi_pkey PRIMARY KEY (id);


--
-- Name: pegawai_gaji pegawai_gaji_pkey; Type: CONSTRAINT; Schema: public; Owner: ppj-pralon
--

ALTER TABLE ONLY public.pegawai_gaji
    ADD CONSTRAINT pegawai_gaji_pkey PRIMARY KEY (id);


--
-- Name: pegawai_gajiborongan pegawai_gajiborongan_pkey; Type: CONSTRAINT; Schema: public; Owner: ppj-pralon
--

ALTER TABLE ONLY public.pegawai_gajiborongan
    ADD CONSTRAINT pegawai_gajiborongan_pkey PRIMARY KEY (id);


--
-- Name: pegawai_pegawai pegawai_pegawai_pkey; Type: CONSTRAINT; Schema: public; Owner: ppj-pralon
--

ALTER TABLE ONLY public.pegawai_pegawai
    ADD CONSTRAINT pegawai_pegawai_pkey PRIMARY KEY (id);


--
-- Name: pegawai_pekerjaanborongan pegawai_pekerjaanborongan_pkey; Type: CONSTRAINT; Schema: public; Owner: ppj-pralon
--

ALTER TABLE ONLY public.pegawai_pekerjaanborongan
    ADD CONSTRAINT pegawai_pekerjaanborongan_pkey PRIMARY KEY (id);


--
-- Name: sales_customercategory sales_customercategory_name_key; Type: CONSTRAINT; Schema: public; Owner: ppj-pralon
--

ALTER TABLE ONLY public.sales_customercategory
    ADD CONSTRAINT sales_customercategory_name_key UNIQUE (name);


--
-- Name: sales_customercategory sales_customercategory_pkey; Type: CONSTRAINT; Schema: public; Owner: ppj-pralon
--

ALTER TABLE ONLY public.sales_customercategory
    ADD CONSTRAINT sales_customercategory_pkey PRIMARY KEY (id);


--
-- Name: zetaapp_excelupload zetaapp_excelupload_pkey; Type: CONSTRAINT; Schema: public; Owner: ppj-pralon
--

ALTER TABLE ONLY public.zetaapp_excelupload
    ADD CONSTRAINT zetaapp_excelupload_pkey PRIMARY KEY (id);


--
-- Name: zetaapp_hutangpiutang zetaapp_hutangpiutang_pkey; Type: CONSTRAINT; Schema: public; Owner: ppj-pralon
--

ALTER TABLE ONLY public.zetaapp_hutangpiutang
    ADD CONSTRAINT zetaapp_hutangpiutang_pkey PRIMARY KEY (id);


--
-- Name: zetaapp_hutpegawai zetaapp_hutpegawai_pkey; Type: CONSTRAINT; Schema: public; Owner: ppj-pralon
--

ALTER TABLE ONLY public.zetaapp_hutpegawai
    ADD CONSTRAINT zetaapp_hutpegawai_pkey PRIMARY KEY (id);


--
-- Name: zetaapp_karyawan zetaapp_karyawan_pkey; Type: CONSTRAINT; Schema: public; Owner: ppj-pralon
--

ALTER TABLE ONLY public.zetaapp_karyawan
    ADD CONSTRAINT zetaapp_karyawan_pkey PRIMARY KEY (id);


--
-- Name: zetaapp_kategori zetaapp_kategori_pkey; Type: CONSTRAINT; Schema: public; Owner: ppj-pralon
--

ALTER TABLE ONLY public.zetaapp_kategori
    ADD CONSTRAINT zetaapp_kategori_pkey PRIMARY KEY (id);


--
-- Name: zetaapp_pegawai zetaapp_pegawai_nip_key; Type: CONSTRAINT; Schema: public; Owner: ppj-pralon
--

ALTER TABLE ONLY public.zetaapp_pegawai
    ADD CONSTRAINT zetaapp_pegawai_nip_key UNIQUE (nip);


--
-- Name: zetaapp_pegawai zetaapp_pegawai_pkey; Type: CONSTRAINT; Schema: public; Owner: ppj-pralon
--

ALTER TABLE ONLY public.zetaapp_pegawai
    ADD CONSTRAINT zetaapp_pegawai_pkey PRIMARY KEY (id);


--
-- Name: zetaapp_product zetaapp_product_pkey; Type: CONSTRAINT; Schema: public; Owner: ppj-pralon
--

ALTER TABLE ONLY public.zetaapp_product
    ADD CONSTRAINT zetaapp_product_pkey PRIMARY KEY (id);


--
-- Name: zetaapp_product zetaapp_product_sku_key; Type: CONSTRAINT; Schema: public; Owner: ppj-pralon
--

ALTER TABLE ONLY public.zetaapp_product
    ADD CONSTRAINT zetaapp_product_sku_key UNIQUE (sku);


--
-- Name: zetaapp_profito2 zetaapp_profito2_pkey; Type: CONSTRAINT; Schema: public; Owner: ppj-pralon
--

ALTER TABLE ONLY public.zetaapp_profito2
    ADD CONSTRAINT zetaapp_profito2_pkey PRIMARY KEY (id);


--
-- Name: zetaapp_profito zetaapp_profito_pkey; Type: CONSTRAINT; Schema: public; Owner: ppj-pralon
--

ALTER TABLE ONLY public.zetaapp_profito
    ADD CONSTRAINT zetaapp_profito_pkey PRIMARY KEY (id);


--
-- Name: zetaapp_stock zetaapp_stock_pkey; Type: CONSTRAINT; Schema: public; Owner: ppj-pralon
--

ALTER TABLE ONLY public.zetaapp_stock
    ADD CONSTRAINT zetaapp_stock_pkey PRIMARY KEY (id);


--
-- Name: zetaapp_stock zetaapp_stock_product_id_key; Type: CONSTRAINT; Schema: public; Owner: ppj-pralon
--

ALTER TABLE ONLY public.zetaapp_stock
    ADD CONSTRAINT zetaapp_stock_product_id_key UNIQUE (product_id);


--
-- Name: zetaapp_stockin zetaapp_stockin_pkey; Type: CONSTRAINT; Schema: public; Owner: ppj-pralon
--

ALTER TABLE ONLY public.zetaapp_stockin
    ADD CONSTRAINT zetaapp_stockin_pkey PRIMARY KEY (id);


--
-- Name: zetaapp_tabungan zetaapp_tabungan_pkey; Type: CONSTRAINT; Schema: public; Owner: ppj-pralon
--

ALTER TABLE ONLY public.zetaapp_tabungan
    ADD CONSTRAINT zetaapp_tabungan_pkey PRIMARY KEY (id);


--
-- Name: zetaapp_task zetaapp_task_pkey; Type: CONSTRAINT; Schema: public; Owner: ppj-pralon
--

ALTER TABLE ONLY public.zetaapp_task
    ADD CONSTRAINT zetaapp_task_pkey PRIMARY KEY (id);


--
-- Name: zetaapp_transaksi zetaapp_transaksi_pkey; Type: CONSTRAINT; Schema: public; Owner: ppj-pralon
--

ALTER TABLE ONLY public.zetaapp_transaksi
    ADD CONSTRAINT zetaapp_transaksi_pkey PRIMARY KEY (id);


--
-- Name: Product_category_75fcd744; Type: INDEX; Schema: public; Owner: ppj-pralon
--

CREATE INDEX "Product_category_75fcd744" ON public."Product" USING btree (category);


--
-- Name: SaleDetails_product_f29895fe; Type: INDEX; Schema: public; Owner: ppj-pralon
--

CREATE INDEX "SaleDetails_product_f29895fe" ON public."SaleDetails" USING btree (product);


--
-- Name: SaleDetails_sale_e37417a9; Type: INDEX; Schema: public; Owner: ppj-pralon
--

CREATE INDEX "SaleDetails_sale_e37417a9" ON public."SaleDetails" USING btree (sale);


--
-- Name: Sales_customer_1832f851; Type: INDEX; Schema: public; Owner: ppj-pralon
--

CREATE INDEX "Sales_customer_1832f851" ON public."Sales" USING btree (customer);


--
-- Name: Sales_transaction_number_7f0dfa9d_like; Type: INDEX; Schema: public; Owner: ppj-pralon
--

CREATE INDEX "Sales_transaction_number_7f0dfa9d_like" ON public."Sales" USING btree (transaction_number varchar_pattern_ops);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: ppj-pralon
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: ppj-pralon
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: ppj-pralon
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: ppj-pralon
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: ppj-pralon
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: ppj-pralon
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: ppj-pralon
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: ppj-pralon
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: ppj-pralon
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: ppj-pralon
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: ppj-pralon
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: ppj-pralon
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: ppj-pralon
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: pegawai_absensi_pegawai_id_9e5b3fd4; Type: INDEX; Schema: public; Owner: ppj-pralon
--

CREATE INDEX pegawai_absensi_pegawai_id_9e5b3fd4 ON public.pegawai_absensi USING btree (pegawai_id);


--
-- Name: pegawai_gaji_pegawai_id_ef4dcda5; Type: INDEX; Schema: public; Owner: ppj-pralon
--

CREATE INDEX pegawai_gaji_pegawai_id_ef4dcda5 ON public.pegawai_gaji USING btree (pegawai_id);


--
-- Name: pegawai_gajiborongan_pegawai_id_b706c6f3; Type: INDEX; Schema: public; Owner: ppj-pralon
--

CREATE INDEX pegawai_gajiborongan_pegawai_id_b706c6f3 ON public.pegawai_gajiborongan USING btree (pegawai_id);


--
-- Name: pegawai_pekerjaanborongan_pegawai_id_8ec0f964; Type: INDEX; Schema: public; Owner: ppj-pralon
--

CREATE INDEX pegawai_pekerjaanborongan_pegawai_id_8ec0f964 ON public.pegawai_pekerjaanborongan USING btree (pegawai_id);


--
-- Name: sales_customercategory_name_2e6f4681_like; Type: INDEX; Schema: public; Owner: ppj-pralon
--

CREATE INDEX sales_customercategory_name_2e6f4681_like ON public.sales_customercategory USING btree (name varchar_pattern_ops);


--
-- Name: zetaapp_hutangpiutang_owner_id_31146618; Type: INDEX; Schema: public; Owner: ppj-pralon
--

CREATE INDEX zetaapp_hutangpiutang_owner_id_31146618 ON public.zetaapp_hutangpiutang USING btree (owner_id);


--
-- Name: zetaapp_hutpegawai_pegawai_id_3f7aa69f; Type: INDEX; Schema: public; Owner: ppj-pralon
--

CREATE INDEX zetaapp_hutpegawai_pegawai_id_3f7aa69f ON public.zetaapp_hutpegawai USING btree (pegawai_id);


--
-- Name: zetaapp_pegawai_nip_4789271e_like; Type: INDEX; Schema: public; Owner: ppj-pralon
--

CREATE INDEX zetaapp_pegawai_nip_4789271e_like ON public.zetaapp_pegawai USING btree (nip varchar_pattern_ops);


--
-- Name: zetaapp_product_sku_d86fcb32_like; Type: INDEX; Schema: public; Owner: ppj-pralon
--

CREATE INDEX zetaapp_product_sku_d86fcb32_like ON public.zetaapp_product USING btree (sku varchar_pattern_ops);


--
-- Name: zetaapp_stockin_product_id_93a32b12; Type: INDEX; Schema: public; Owner: ppj-pralon
--

CREATE INDEX zetaapp_stockin_product_id_93a32b12 ON public.zetaapp_stockin USING btree (product_id);


--
-- Name: zetaapp_stockin_received_by_id_0db91cd2; Type: INDEX; Schema: public; Owner: ppj-pralon
--

CREATE INDEX zetaapp_stockin_received_by_id_0db91cd2 ON public.zetaapp_stockin USING btree (received_by_id);


--
-- Name: zetaapp_tabungan_owner_id_fc4ae933; Type: INDEX; Schema: public; Owner: ppj-pralon
--

CREATE INDEX zetaapp_tabungan_owner_id_fc4ae933 ON public.zetaapp_tabungan USING btree (owner_id);


--
-- Name: zetaapp_transaksi_kategori_id_f333bb32; Type: INDEX; Schema: public; Owner: ppj-pralon
--

CREATE INDEX zetaapp_transaksi_kategori_id_f333bb32 ON public.zetaapp_transaksi USING btree (kategori_id);


--
-- Name: zetaapp_transaksi_owner_id_705c64c3; Type: INDEX; Schema: public; Owner: ppj-pralon
--

CREATE INDEX zetaapp_transaksi_owner_id_705c64c3 ON public.zetaapp_transaksi USING btree (owner_id);


--
-- Name: Product Product_category_75fcd744_fk_Category_id; Type: FK CONSTRAINT; Schema: public; Owner: ppj-pralon
--

ALTER TABLE ONLY public."Product"
    ADD CONSTRAINT "Product_category_75fcd744_fk_Category_id" FOREIGN KEY (category) REFERENCES public."Category"(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: SaleDetails SaleDetails_product_f29895fe_fk_Product_id; Type: FK CONSTRAINT; Schema: public; Owner: ppj-pralon
--

ALTER TABLE ONLY public."SaleDetails"
    ADD CONSTRAINT "SaleDetails_product_f29895fe_fk_Product_id" FOREIGN KEY (product) REFERENCES public."Product"(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: SaleDetails SaleDetails_sale_e37417a9_fk_Sales_id; Type: FK CONSTRAINT; Schema: public; Owner: ppj-pralon
--

ALTER TABLE ONLY public."SaleDetails"
    ADD CONSTRAINT "SaleDetails_sale_e37417a9_fk_Sales_id" FOREIGN KEY (sale) REFERENCES public."Sales"(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: Sales Sales_customer_1832f851_fk_Customers_id; Type: FK CONSTRAINT; Schema: public; Owner: ppj-pralon
--

ALTER TABLE ONLY public."Sales"
    ADD CONSTRAINT "Sales_customer_1832f851_fk_Customers_id" FOREIGN KEY (customer) REFERENCES public."Customers"(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: ppj-pralon
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: ppj-pralon
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: ppj-pralon
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: ppj-pralon
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: ppj-pralon
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: ppj-pralon
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: ppj-pralon
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: authentication_profile authentication_profile_user_id_d23cdeb4_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: ppj-pralon
--

ALTER TABLE ONLY public.authentication_profile
    ADD CONSTRAINT authentication_profile_user_id_d23cdeb4_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: ppj-pralon
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: ppj-pralon
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: pegawai_absensi pegawai_absensi_pegawai_id_9e5b3fd4_fk_pegawai_pegawai_id; Type: FK CONSTRAINT; Schema: public; Owner: ppj-pralon
--

ALTER TABLE ONLY public.pegawai_absensi
    ADD CONSTRAINT pegawai_absensi_pegawai_id_9e5b3fd4_fk_pegawai_pegawai_id FOREIGN KEY (pegawai_id) REFERENCES public.pegawai_pegawai(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: pegawai_gaji pegawai_gaji_pegawai_id_ef4dcda5_fk_pegawai_pegawai_id; Type: FK CONSTRAINT; Schema: public; Owner: ppj-pralon
--

ALTER TABLE ONLY public.pegawai_gaji
    ADD CONSTRAINT pegawai_gaji_pegawai_id_ef4dcda5_fk_pegawai_pegawai_id FOREIGN KEY (pegawai_id) REFERENCES public.pegawai_pegawai(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: pegawai_gajiborongan pegawai_gajiborongan_pegawai_id_b706c6f3_fk_pegawai_pegawai_id; Type: FK CONSTRAINT; Schema: public; Owner: ppj-pralon
--

ALTER TABLE ONLY public.pegawai_gajiborongan
    ADD CONSTRAINT pegawai_gajiborongan_pegawai_id_b706c6f3_fk_pegawai_pegawai_id FOREIGN KEY (pegawai_id) REFERENCES public.pegawai_pegawai(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: pegawai_pekerjaanborongan pegawai_pekerjaanbor_pegawai_id_8ec0f964_fk_pegawai_p; Type: FK CONSTRAINT; Schema: public; Owner: ppj-pralon
--

ALTER TABLE ONLY public.pegawai_pekerjaanborongan
    ADD CONSTRAINT pegawai_pekerjaanbor_pegawai_id_8ec0f964_fk_pegawai_p FOREIGN KEY (pegawai_id) REFERENCES public.pegawai_pegawai(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: zetaapp_hutangpiutang zetaapp_hutangpiutang_owner_id_31146618_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: ppj-pralon
--

ALTER TABLE ONLY public.zetaapp_hutangpiutang
    ADD CONSTRAINT zetaapp_hutangpiutang_owner_id_31146618_fk_auth_user_id FOREIGN KEY (owner_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: zetaapp_hutpegawai zetaapp_hutpegawai_pegawai_id_3f7aa69f_fk_zetaapp_karyawan_id; Type: FK CONSTRAINT; Schema: public; Owner: ppj-pralon
--

ALTER TABLE ONLY public.zetaapp_hutpegawai
    ADD CONSTRAINT zetaapp_hutpegawai_pegawai_id_3f7aa69f_fk_zetaapp_karyawan_id FOREIGN KEY (pegawai_id) REFERENCES public.zetaapp_karyawan(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: zetaapp_stock zetaapp_stock_product_id_1e1d7eb0_fk_zetaapp_product_id; Type: FK CONSTRAINT; Schema: public; Owner: ppj-pralon
--

ALTER TABLE ONLY public.zetaapp_stock
    ADD CONSTRAINT zetaapp_stock_product_id_1e1d7eb0_fk_zetaapp_product_id FOREIGN KEY (product_id) REFERENCES public.zetaapp_product(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: zetaapp_stockin zetaapp_stockin_product_id_93a32b12_fk_zetaapp_product_id; Type: FK CONSTRAINT; Schema: public; Owner: ppj-pralon
--

ALTER TABLE ONLY public.zetaapp_stockin
    ADD CONSTRAINT zetaapp_stockin_product_id_93a32b12_fk_zetaapp_product_id FOREIGN KEY (product_id) REFERENCES public.zetaapp_product(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: zetaapp_stockin zetaapp_stockin_received_by_id_0db91cd2_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: ppj-pralon
--

ALTER TABLE ONLY public.zetaapp_stockin
    ADD CONSTRAINT zetaapp_stockin_received_by_id_0db91cd2_fk_auth_user_id FOREIGN KEY (received_by_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: zetaapp_tabungan zetaapp_tabungan_owner_id_fc4ae933_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: ppj-pralon
--

ALTER TABLE ONLY public.zetaapp_tabungan
    ADD CONSTRAINT zetaapp_tabungan_owner_id_fc4ae933_fk_auth_user_id FOREIGN KEY (owner_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: zetaapp_transaksi zetaapp_transaksi_kategori_id_f333bb32_fk_zetaapp_kategori_id; Type: FK CONSTRAINT; Schema: public; Owner: ppj-pralon
--

ALTER TABLE ONLY public.zetaapp_transaksi
    ADD CONSTRAINT zetaapp_transaksi_kategori_id_f333bb32_fk_zetaapp_kategori_id FOREIGN KEY (kategori_id) REFERENCES public.zetaapp_kategori(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: zetaapp_transaksi zetaapp_transaksi_owner_id_705c64c3_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: ppj-pralon
--

ALTER TABLE ONLY public.zetaapp_transaksi
    ADD CONSTRAINT zetaapp_transaksi_owner_id_705c64c3_fk_auth_user_id FOREIGN KEY (owner_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict hCxehQa7qRf5Apw8cU00RuIBTZVr8jyKNYD9TrBsbdo4HBQOKoDw4ulWgaY5nGk

