# Generated by Django 5.2.7 on 2026-08-03 10:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0008_sale_dp_amount_sale_is_afkiran'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Afkiran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dp_amount', models.FloatField(default=0, verbose_name='DP (Uang Muka)')),
                ('total_nota', models.FloatField(default=0, verbose_name='Total Nota PS Kaca')),
                ('total_sortir', models.FloatField(default=0, verbose_name='Total Nilai Sortir')),
                ('selisih', models.FloatField(default=0, verbose_name='Selisih (Nota - Sortir)')),
                ('sisa_bayar', models.FloatField(default=0, verbose_name='Sisa Bayar (Selisih - DP)')),
                ('status', models.CharField(choices=[('PENDING', 'Menunggu Pelunasan'), ('LUNAS', 'Sudah Lunas')], default='PENDING', max_length=10, verbose_name='Status')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('catatan', models.TextField(blank=True, default='', verbose_name='Catatan')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('sale', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='afkiran', to='sales.sale', verbose_name='Nota Barang Masuk')),
            ],
            options={
                'verbose_name': 'Afkiran',
                'verbose_name_plural': 'Daftar Afkiran',
                'db_table': 'Afkiran',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='AfkiranDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_barang', models.CharField(choices=[('ps_kaca', 'PS Kaca'), ('ps_warna', 'PS Warna'), ('cd', 'CD'), ('akralik', 'Akralik'), ('pc', 'PC'), ('as_item', 'AS'), ('dop', 'Dop'), ('krasan', 'Krasan')], max_length=50, verbose_name='Jenis Barang')),
                ('quantity', models.FloatField(default=0, verbose_name='Jumlah (kg)')),
                ('harga', models.FloatField(default=0, verbose_name='Harga/kg')),
                ('total', models.FloatField(default=0, verbose_name='Total')),
                ('afkiran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afkiran.afkiran', verbose_name='Afkiran')),
            ],
            options={
                'db_table': 'AfkiranDetail',
            },
        ),
    ]
