# Generated by Django 5.2.7 on 2026-08-08 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afkiran', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afkirandetail',
            name='nama_barang',
            field=models.CharField(choices=[('ps kaca', 'PS Kaca'), ('ps warna', 'PS Warna'), ('cd', 'CD'), ('akralik', 'Akralik'), ('pc', 'PC'), ('as item', 'AS'), ('dop', 'Dop'), ('krasan', 'Krasan')], max_length=50, verbose_name='Jenis Barang'),
        ),
    ]
