# Generated by Django 5.0 on 2024-01-28 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Karyawan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pegawai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('nip', models.CharField(max_length=20, unique=True)),
                ('jabatan', models.CharField(max_length=50)),
                ('gaji', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tanggal_masuk', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Profito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_suplayer', models.TextField()),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('jumlah_brg', models.DecimalField(decimal_places=2, max_digits=20)),
                ('harga_jual', models.DecimalField(decimal_places=2, max_digits=20)),
                ('harga_beli', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tabungan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaksi_choice', models.CharField(choices=[('P', 'Pemasukan'), ('L', 'Pengeluaran')], max_length=1)),
                ('nominal', models.DecimalField(decimal_places=2, max_digits=20)),
                ('description', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('complete', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HutangPiutang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.DecimalField(decimal_places=2, max_digits=20)),
                ('tanggal', models.DateField()),
                ('hutang_choice', models.CharField(choices=[('H', 'Hutang'), ('P', 'Piutang')], max_length=1)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hutang', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HutPegawai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.DecimalField(decimal_places=2, max_digits=20)),
                ('tanggal', models.DateTimeField()),
                ('hutang_choice', models.CharField(choices=[('H', 'Hutang'), ('P', 'Piutang')], max_length=1)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('pegawai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zetaapp.karyawan')),
            ],
        ),
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.DecimalField(decimal_places=2, max_digits=20)),
                ('tanggal', models.DateTimeField()),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('transaksi_choice', models.CharField(choices=[('P', 'Pemasukan'), ('L', 'Pengeluaran')], max_length=1)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zetaapp.kategori')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transaksi', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
