# Generated by Django 5.2.7 on 2025-12-11 07:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excel_files', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Karyawan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pegawai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('nip', models.CharField(max_length=20, unique=True)),
                ('jabatan', models.CharField(max_length=50)),
                ('gaji', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tanggal_masuk', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Profito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_suplayer', models.TextField()),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('jumlah_brg', models.DecimalField(decimal_places=2, max_digits=20)),
                ('harga_jual', models.DecimalField(decimal_places=2, max_digits=20)),
                ('harga_beli', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Profito2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('nama_barang', models.CharField(max_length=100)),
                ('berat_input', models.DecimalField(decimal_places=2, max_digits=10)),
                ('harga_beli_per_kg', models.DecimalField(decimal_places=0, max_digits=15)),
                ('harga_jual_per_kg', models.DecimalField(decimal_places=0, max_digits=15)),
                ('solar', models.DecimalField(decimal_places=0, default=100, max_digits=15)),
                ('karung', models.DecimalField(decimal_places=0, default=50, max_digits=15)),
                ('ongkos_kirim', models.DecimalField(decimal_places=0, default=375, max_digits=15)),
                ('ongkos_sortir', models.DecimalField(decimal_places=0, default=300, max_digits=15)),
                ('ongkos_giling', models.DecimalField(decimal_places=0, default=300, max_digits=15)),
                ('ongkos_muat', models.DecimalField(decimal_places=0, default=50, max_digits=15)),
                ('susutan_persen', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('berat_output', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('hpp_per_kg', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True)),
                ('total_hpp', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True)),
                ('total_revenue', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True)),
                ('profit', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True)),
                ('profit_margin', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('tabungan_persen', models.DecimalField(decimal_places=2, default=30, max_digits=5)),
                ('tabungan_total', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True)),
                ('profit_saved', models.BooleanField(default=False)),
                ('keterangan', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-tanggal'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('complete', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HutangPiutang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.DecimalField(decimal_places=2, max_digits=20)),
                ('tanggal', models.DateField()),
                ('hutang_choice', models.CharField(choices=[('H', 'Hutang'), ('P', 'Piutang')], max_length=1)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hutang', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HutPegawai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.DecimalField(decimal_places=2, max_digits=20)),
                ('tanggal', models.DateField()),
                ('hutang_choice', models.CharField(choices=[('H', 'Hutang'), ('P', 'Piutang')], max_length=1)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hutangpeg', to=settings.AUTH_USER_MODEL)),
                ('pegawai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zetaapp.karyawan')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='zetaapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='StockIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference', models.CharField(blank=True, max_length=200)),
                ('note', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_in_history', to='zetaapp.product')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tabungan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nominal', models.DecimalField(decimal_places=2, max_digits=20)),
                ('description', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tabungans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.DecimalField(decimal_places=2, max_digits=20)),
                ('tanggal', models.DateField()),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('transaksi_choice', models.CharField(blank=True, choices=[('P', 'Pemasukan'), ('L', 'Pengeluaran')], max_length=1, null=True)),
                ('kategori', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zetaapp.kategori')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transaksi', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
