# Generated by Django 5.0 on 2024-01-19 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zetaapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tabungan',
            name='Pemasukan',
        ),
        migrations.RemoveField(
            model_name='tabungan',
            name='Pengeluaran',
        ),
        migrations.AddField(
            model_name='tabungan',
            name='nominal',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tabungan',
            name='transaksi_choice',
            field=models.CharField(choices=[('P', 'Pemasukan'), ('L', 'Pengeluaran')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hutangpiutang',
            name='jumlah',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='profito',
            name='harga_beli',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='profito',
            name='harga_jual',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='profito',
            name='jumlah_brg',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='transaksi',
            name='jumlah',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
