# Generated by Django 5.0 on 2025-03-07 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zetaapp', '0002_excelupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hutpegawai',
            name='tanggal',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='transaksi',
            name='tanggal',
            field=models.DateField(),
        ),
    ]
