# Generated by Django 5.2.7 on 2025-12-14 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zetaapp', '0002_kategori_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kategori',
            name='owner',
        ),
    ]
