# Generated by Django 5.0 on 2025-03-07 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zetaapp', '0003_alter_hutpegawai_tanggal_alter_transaksi_tanggal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaksi',
            name='kategori',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zetaapp.kategori'),
        ),
        migrations.AlterField(
            model_name='transaksi',
            name='transaksi_choice',
            field=models.CharField(blank=True, choices=[('P', 'Pemasukan'), ('L', 'Pengeluaran')], max_length=1, null=True),
        ),
    ]
