# Generated by Django 5.2.7 on 2025-11-10 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_customercategory'),
        ('zetaapp', '0004_alter_transaksi_kategori_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksi',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.sale'),
        ),
    ]
