# Generated by Django 5.2.7 on 2025-11-10 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zetaapp', '0005_transaksi_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaksi',
            name='sale',
        ),
    ]
