# Generated by Django 5.2.7 on 2025-11-14 15:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zetaapp', '0006_remove_transaksi_sale'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profito2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('nama_barang', models.CharField(max_length=100)),
                ('harga_beli', models.DecimalField(decimal_places=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('harga_jual', models.DecimalField(decimal_places=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('solar', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('karung', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('ongkos_kirim', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('ongkos_muat', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('ongkos_lain', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('ongkos_sortir', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('ongkos_giling', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('biaya_darurat_mesin', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('hpp', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True)),
                ('profit', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True)),
                ('profit_margin', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('keterangan', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-tanggal'],
            },
        ),
    ]
