# Generated by Django 5.2.7 on 2025-11-17 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zetaapp', '0008_product_stock_stockin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profito2',
            old_name='hpp',
            new_name='hpp_per_kg',
        ),
        migrations.RemoveField(
            model_name='profito2',
            name='biaya_darurat_mesin',
        ),
        migrations.RemoveField(
            model_name='profito2',
            name='harga_beli',
        ),
        migrations.RemoveField(
            model_name='profito2',
            name='harga_jual',
        ),
        migrations.RemoveField(
            model_name='profito2',
            name='keterangan',
        ),
        migrations.RemoveField(
            model_name='profito2',
            name='ongkos_lain',
        ),
        migrations.AddField(
            model_name='profito2',
            name='berat_input',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profito2',
            name='berat_output',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='profito2',
            name='harga_beli_per_kg',
            field=models.DecimalField(decimal_places=0, default=131, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profito2',
            name='harga_jual_per_kg',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profito2',
            name='susutan_persen',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='profito2',
            name='total_hpp',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='profito2',
            name='total_revenue',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='profito2',
            name='karung',
            field=models.DecimalField(decimal_places=0, default=50, max_digits=15),
        ),
        migrations.AlterField(
            model_name='profito2',
            name='ongkos_giling',
            field=models.DecimalField(decimal_places=0, default=300, max_digits=15),
        ),
        migrations.AlterField(
            model_name='profito2',
            name='ongkos_kirim',
            field=models.DecimalField(decimal_places=0, default=375, max_digits=15),
        ),
        migrations.AlterField(
            model_name='profito2',
            name='ongkos_muat',
            field=models.DecimalField(decimal_places=0, default=50, max_digits=15),
        ),
        migrations.AlterField(
            model_name='profito2',
            name='ongkos_sortir',
            field=models.DecimalField(decimal_places=0, default=300, max_digits=15),
        ),
        migrations.AlterField(
            model_name='profito2',
            name='solar',
            field=models.DecimalField(decimal_places=0, default=100, max_digits=15),
        ),
    ]
