# Generated by Django 5.2.7 on 2025-11-17 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zetaapp', '0009_rename_hpp_profito2_hpp_per_kg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profito2',
            name='keterangan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profito2',
            name='tabungan_persen',
            field=models.DecimalField(decimal_places=2, default=30, max_digits=5),
        ),
        migrations.AddField(
            model_name='profito2',
            name='tabungan_total',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True),
        ),
    ]
