# Generated by Django 5.2.7 on 2025-11-24 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zetaapp', '0010_profito2_keterangan_profito2_tabungan_persen_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tabungan',
            name='transaksi_choice',
        ),
        migrations.AddField(
            model_name='profito2',
            name='profit_saved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tabungan',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tabungans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tabungan',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
