# Generated by Django 5.2.7 on 2025-12-05 05:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zetaapp', '0011_remove_tabungan_transaksi_choice_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hutpegawai',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hutangpeg', to=settings.AUTH_USER_MODEL),
        ),
    ]
