# Generated by Django 5.2.7 on 2026-07-25 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zetaapp', '0004_kategori_owner'),
        ('zetaapp', '0011_remove_tabungan_transaksi_choice_and_more'),
    ]

    operations = [
        migrations.RunPython(migrations.RunPython.noop, migrations.RunPython.noop),
    ]
