# Generated by Django 5.2.7 on 2026-07-26 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_code_alter_product_name'),
        ('zetaapp', '0012_merge_20260725_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockin',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_in_history', to='products.product'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='products.product'),
        ),
        migrations.RemoveField(
            model_name='transaksi',
            name='sale',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
