# Generated by Django 5.2.7 on 2026-08-08 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_owner'),
        ('zetaapp', '0013_alter_stockin_product_alter_stock_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabungan',
            name='customer',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='customers.customer'),
            preserve_default=False,
        ),
    ]
