# Generated by Django 5.2.7 on 2026-08-08 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zetaapp', '0014_tabungan_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tabungan',
            name='customer',
        ),
    ]
