# Generated by Django 5.2.7 on 2026-08-09 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_purchase_biaya_lain_purchase_gaji_pegawai_and_more'),
        ('zetaapp', '0015_remove_tabungan_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='profito2',
            name='gaji_pegawai',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='profito2',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profit_entries', to='purchases.purchase'),
        ),
    ]
