# Generated by Django 5.2.7 on 2026-09-03 13:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zetaapp', '0016_profito2_gaji_pegawai_profito2_purchase'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BiayaBulanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(default=django.utils.timezone.now)),
                ('kategori', models.CharField(choices=[('Operasional', 'Operasional'), ('Gaji Pegawai', 'Gaji Pegawai'), ('Sewa Tempat', 'Sewa Tempat'), ('Listrik & Air', 'Listrik & Air'), ('Transportasi & BBM', 'Transportasi & BBM'), ('Pemeliharaan & Servis', 'Pemeliharaan & Servis'), ('Internet & Komunikasi', 'Internet & Komunikasi'), ('Administrasi & Pajak', 'Administrasi & Pajak'), ('Lain-lain', 'Lain-lain')], default='Operasional', max_length=100)),
                ('nama_biaya', models.CharField(max_length=200, verbose_name='Nama Biaya')),
                ('nominal', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Nominal (Rp)')),
                ('keterangan', models.TextField(blank=True, null=True, verbose_name='Keterangan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biaya_bulanan', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Biaya Bulanan',
                'verbose_name_plural': 'Biaya Bulanan',
                'db_table': 'biaya_bulanan',
                'ordering': ['-tanggal', '-id'],
            },
        ),
    ]
