# Generated by Django 5.2.7 on 2026-08-09 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_alter_purchasedetail_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='biaya_lain',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='purchase',
            name='gaji_pegawai',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='purchase',
            name='net_profit',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='purchase',
            name='ongkos_muat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='purchase',
            name='profit_kotor',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='purchase',
            name='susutan_persen',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='purchase',
            name='tabungan_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='purchase',
            name='tabungan_persen',
            field=models.FloatField(default=30),
        ),
    ]
