# Generated by Django 5.2.7 on 2026-08-12 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_purchase_biaya_lain_purchase_gaji_pegawai_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='amount_change',
            field=models.FloatField(default=0, verbose_name='Kembalian'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='amount_payed',
            field=models.FloatField(default=0, verbose_name='Nominal Bayar'),
        ),
    ]
