# Generated by Django 5.0 on 2025-03-29 15:04

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pegawai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('posisi', models.CharField(choices=[('Borongan', 'Borongan'), ('Harian', 'Harian')], max_length=10)),
                ('tanggal_masuk', models.DateField()),
                ('status', models.CharField(choices=[('Aktif', 'Aktif'), ('Resign', 'Resign')], max_length=50)),
                ('gaji_harian', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='GajiBorongan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minggu_mulai', models.DateField(default=datetime.date.today)),
                ('minggu_selesai', models.DateField()),
                ('total_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('harga_per_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_gaji', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved')], default='Pending', max_length=10)),
                ('pegawai', models.ForeignKey(limit_choices_to={'posisi': 'Borongan'}, on_delete=django.db.models.deletion.CASCADE, to='pegawai.pegawai')),
            ],
        ),
        migrations.CreateModel(
            name='Gaji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minggu_mulai', models.DateField(default=datetime.date.today)),
                ('minggu_selesai', models.DateField()),
                ('total_hadir', models.IntegerField(default=0, editable=False)),
                ('total_gaji', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved')], default='Pending', max_length=10)),
                ('pegawai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pegawai.pegawai')),
            ],
        ),
        migrations.CreateModel(
            name='Absensi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('jam_masuk', models.TimeField(blank=True, null=True)),
                ('jam_keluar', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Hadir', 'Hadir'), ('Izin', 'Izin'), ('Sakit', 'Sakit'), ('Alpa', 'Alpa')], default='Hadir', max_length=10)),
                ('pegawai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pegawai.pegawai')),
            ],
        ),
        migrations.CreateModel(
            name='PekerjaanBorongan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minggu_mulai', models.DateField(default=datetime.date.today)),
                ('minggu_selesai', models.DateField()),
                ('total_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('harga_per_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_gaji', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('pegawai', models.ForeignKey(limit_choices_to={'posisi': 'Borongan'}, on_delete=django.db.models.deletion.CASCADE, to='pegawai.pegawai')),
            ],
        ),
    ]
