# Generated by Django 5.0 on 2024-02-25 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='alamat',
        ),
    ]
