# Generated by Django 5.0 on 2024-02-25 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_profile_alamat'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='alamat',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nama_lengkap',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
