# Generated by Django 5.0 on 2024-03-09 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='transaction_number',
            field=models.CharField(default=10, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
