# Generated by Django 5.2.7 on 2025-12-11 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='owner',
        ),
    ]
