# Generated by Django 5.0 on 2024-07-25 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_sale_transaction_number'),
    ]

    operations = [
    ]

