# Generated by Django 5.2.7 on 2026-07-25 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_sale_owner'),
        ('sales', '0004_customercategory'),
    ]

    operations = [
    ]
