# Generated by Django 5.2.7 on 2026-07-25 10:37
# Updated: merge migration simplified after fixing 0004 dependency

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_remove_sale_tax_amount_remove_sale_tax_percentage'),
        ('sales', '0004_customercategory'),
    ]

    operations = [
    ]
