# Generated by Django 5.2.7 on 2025-12-05 04:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_customercategory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerCategory',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='customer',
        ),
        migrations.AddField(
            model_name='sale',
            name='owner',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
