# Generated by Django 5.2.7 on 2026-07-30 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_alter_saledetail_product_alter_saledetail_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saledetail',
            name='quantity',
            field=models.FloatField(default=0),
        ),
    ]
