# Generated by Django 5.2.7 on 2026-08-03 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_alter_saledetail_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='dp_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sale',
            name='is_afkiran',
            field=models.BooleanField(default=False),
        ),
    ]
