# Generated by Django 5.2.7 on 2026-08-08 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_sale_dp_amount_sale_is_afkiran'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerCategory',
        ),
    ]
