# Generated by Django 5.2.7 on 2025-12-05 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_owner_product_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='owner',
        ),
    ]
