# Generated by Django 5.2.7 on 2025-12-05 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_category_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='product',
            name='owner',
        ),
    ]
