# Generated by Django 5.2.7 on 2026-08-08 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_code_alter_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='selling_price',
            field=models.FloatField(default=0, verbose_name='Harga Jual'),
        ),
    ]
